function screenshots(folder, files) {
  return files.map(([file, alt, caption]) => ({
    src: `/screenshots/${folder}/${file}`,
    alt,
    caption
  }));
}

// US Microsoft Store pricing, verified against the publisher catalog.
// Keep pricing centralized so cards, product pages, and structured data agree.
const usdPrices = {
  BGT: { current: '14.99', original: '19.99', discountPercent: 25 },
  BGI: { current: '14.99', original: '19.99', discountPercent: 25 },
  BT: { current: '14.99', original: '19.99', discountPercent: 25 },
  BFO: { current: '3.74', original: '4.99', discountPercent: 25 },
  BEI: { current: '3.74', original: '4.99', discountPercent: 25 },
  BRI: { current: '3.74', original: '4.99', discountPercent: 25 },
  BWI: { current: '3.74', original: '4.99', discountPercent: 25 },
  BCI: { current: '3.74', original: '4.99', discountPercent: 25 },
  BMP: { current: '3.74', original: '4.99', discountPercent: 25 },
  BSP: { current: '3.74', original: '4.99', discountPercent: 25 },
  BTP: { current: '3.74', original: '4.99', discountPercent: 25 },
  BCP: { current: '3.74', original: '4.99', discountPercent: 25 },
  BWP: { current: '3.74', original: '4.99', discountPercent: 25 },
  BPP: { current: '3.74', original: '4.99', discountPercent: 25 },
  KR: { current: '3.74', original: '4.99', discountPercent: 25 },
  CWAI: { current: '11.24', original: '14.99', discountPercent: 25 }
};

const products = [
  {
    code: 'BGT',
    slug: 'batchgen-text',
    url: '/batchgen-text.html',
    name: 'Batch Generate Text with any AI',
    seoTitle: 'Batch Generate Text with any AI — Batch AI Writer for Windows | 3thousand30',
    shortName: 'Batch Generate Text with any AI',
    type: 'ai',
    typeLabel: 'AI creation',
    categories: ['writing', 'publishing', 'social'],
    status: 'released',
    featured: true,
    tagline: 'Turn a topic list into a reviewed batch of writing with your own AI provider.',
    description: 'Bulk AI writing for Windows with reusable personas, sample analysis, CSV topic lists, multiple providers, and local Markdown or text outputs.',
    intro: 'Batch Generate Text with any AI is built for writing jobs that repeat: social posts, article drafts, product copy, poems, stories, and custom formats. Set the structure once, preview one result, review the batch, and keep the saved files on your PC.',
    logo: '/Logos/BGT.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9n3b1b8dt39f',
    docsUrl: 'https://3thousand30.github.io/batchgentext-docs/',
    privacyLabel: 'BYO key · local outputs',
    privacyText: 'API keys are encrypted locally with Windows DPAPI and finished files are saved to your PC. Prompts are sent only to the external AI provider you choose.',
    features: [
      'Generate complete batches from a CSV topic list',
      'Save multiple AI provider and model connections',
      'Use reusable personas and writing samples for consistency',
      'Create posts, threads, articles, product copy, and custom formats',
      'Preview before committing to a full batch',
      'Save finished work locally as Markdown or plain text'
    ],
    audiences: ['Creators building a repeatable content system', 'Publishers preparing stories, poems, or chapters', 'Small teams producing structured copy without another subscription'],
    screenshotItems: screenshots('bgt', [
      ['1.webp', 'Batch Generate Text with any AI topic and template setup', 'Choose the format and prepare the batch.'],
      ['2.webp', 'Provider and model selection in Batch Generate Text with any AI', 'Bring the provider and model that fit the job.'],
      ['3.webp', 'Persona controls for consistent batch writing', 'Reuse a voice and writing rules across the set.'],
      ['6.webp', 'Completed Batch Generate Text with any AI files saved locally', 'Review the completed run and keep the outputs locally.']
    ]),
    faq: [
      { q: 'Does it include AI usage?', a: 'No. You bring your own provider key and pay that provider directly, so you can choose the model and cost profile.' },
      { q: 'Where are outputs stored?', a: 'Generated Markdown or text files are saved to the folder you choose on your Windows PC.' },
      { q: 'Is the whole workflow offline?', a: 'The app and saved outputs are local. Generation requires a connection to the external AI provider you selected.' }
    ],
    relatedProducts: ['BGI', 'BT', 'BTP'],
    relatedUseCases: ['generate-product-descriptions-from-csv-with-ai', 'mass-create-social-media-content', 'create-short-stories-for-teaching', 'create-a-poetry-book', 'create-song-lyrics-for-inspiration'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BGI',
    slug: 'batchgen-image',
    url: '/batchgen-image.html',
    name: 'Batch Generate Image with any AI',
    seoTitle: 'Batch Generate Image with any AI — Bulk Image Generator for Windows | 3thousand30',
    shortName: 'Batch Generate Image with any AI',
    type: 'ai',
    typeLabel: 'AI creation',
    categories: ['images', 'publishing', 'social'],
    status: 'released',
    featured: true,
    tagline: 'Generate coherent image sets for campaigns, books, posters, and product ideas.',
    description: 'Bulk AI image generation on Windows with your own provider, reusable visual personas, styles, reference images, captions, and local outputs.',
    intro: 'Batch Generate Image with any AI is for projects that need an image set rather than one lucky prompt. Build the list, choose a visual direction, generate more than you need, and keep human selection at the centre of the workflow.',
    logo: '/Logos/BGI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9pfr4v6827xq',
    docsUrl: 'https://3thousand30.github.io/batchgenimage-docs/',
    privacyLabel: 'BYO key · local outputs',
    privacyText: 'Your provider receives the generation request you choose to send. API keys are encrypted locally and generated images are saved on your machine rather than a 3thousand30 cloud.',
    features: [
      'Generate image batches from a prepared topic list',
      'Choose your own compatible provider and model',
      'Reuse visual personas, styles, and reference images',
      'Use templates for posters, covers, social posts, or custom ratios',
      'Add captions when image-and-text output is useful',
      'Keep every generated file in a local project folder'
    ],
    audiences: ['Creators planning visual series', 'Authors and publishers building illustrated artifacts', 'Sellers preparing posters, concepts, and campaign imagery'],
    screenshotItems: screenshots('bgi', [
      ['1.webp', 'Batch Generate Image with any AI project setup', 'Set up the image batch and output direction.'],
      ['2.webp', 'Batch Generate Image with any AI template and prompt controls', 'Choose a reusable format for the set.'],
      ['4.webp', 'Generated image batch review', 'Generate enough candidates to make a real selection.'],
      ['5.webp', 'Batch Generate Image with any AI local output view', 'Keep the selected image files on your PC.']
    ]),
    faq: [
      { q: 'Does it include image-generation credits?', a: 'No. You use your own provider key, choose the model, and pay the provider directly.' },
      { q: 'Can it keep a whole series consistent?', a: 'Visual personas, styles, references, and reusable templates help, but you should still generate alternatives and review the set carefully.' },
      { q: 'Where are the generated images saved?', a: 'The files are saved locally in the output folder you choose.' }
    ],
    relatedProducts: ['BGT', 'BEI', 'BRI'],
    relatedUseCases: ['create-a-photobook-with-ai-for-gifting', 'batch-create-images-for-social-media', 'create-a-colouring-book-for-children', 'create-posters-to-print-or-sell'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BT',
    slug: 'batchtranslate',
    url: '/batchtranslate.html',
    name: 'Batch Translate Text with any AI',
    seoTitle: 'Batch Translate Text with any AI — Document Translator for Windows | 3thousand30',
    shortName: 'Batch Translate Text with any AI',
    type: 'ai',
    typeLabel: 'AI translation',
    categories: ['translation', 'writing', 'publishing'],
    status: 'released',
    featured: true,
    tagline: 'Translate folders of documents into one or more languages with your own provider.',
    description: 'Batch-translate PDF, DOCX, TXT, and Markdown files on Windows using your own AI key and save each result locally.',
    intro: 'Batch Translate Text with any AI turns a folder of documents into a managed translation run. Choose the target languages, provider, and model, then review the saved results before they become public editions.',
    logo: '/Logos/BT.png',
    storeUrl: 'https://apps.microsoft.com/detail/9N75DWR9X2S7',
    docsUrl: 'https://3thousand30.github.io/batchtranslate-docs/',
    privacyLabel: 'BYO key · local outputs',
    privacyText: 'Source content is sent to the external AI provider you select for translation. Keys are encrypted locally and the translated files are saved on your PC.',
    features: ['Process PDF, DOCX, TXT, and Markdown files', 'Translate a batch into one or more target languages', 'Choose your own provider and model', 'Save provider configurations for repeat work', 'Track progress across the folder', 'Store every translated result locally'],
    audiences: ['Independent publishers preparing new language editions', 'Teams localising document sets', 'Creators republishing finished content for another audience'],
    screenshotItems: screenshots('bt', [
      ['1.webp', 'Batch Translate Text with any AI document and language setup', 'Select the source folder and target languages.'],
      ['2.webp', 'AI provider controls in Batch Translate Text with any AI', 'Choose the provider and model for the run.'],
      ['3.webp', 'Batch translation progress view', 'Follow the document batch as it is translated.'],
      ['4.webp', 'Translated files saved from Batch Translate Text with any AI', 'Review the translated outputs locally.']
    ]),
    faq: [
      { q: 'Which files can it translate?', a: 'It supports PDF, DOCX, TXT, and Markdown sources stored in local folders.' },
      { q: 'Does translation still need review?', a: 'Yes. Names, tone, formatting, terminology, and culturally sensitive wording need human review before publication.' },
      { q: 'Does 3thousand30 store my documents?', a: 'No. The selected AI provider receives the translation request; 3thousand30 does not add another cloud-storage layer.' }
    ],
    relatedProducts: ['BGT', 'BTP', 'BMP'],
    relatedUseCases: ['translate-multiple-documents-with-ai', 'publish-content-in-different-languages', 'translate-a-book-for-new-markets'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BFO',
    slug: 'batchfile-organiser',
    url: '/batchfile-organiser.html',
    name: 'Batch File Organiser',
    seoTitle: 'Batch File Organiser — File Organiser for Windows | 3thousand30',
    shortName: 'Batch File Organiser',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['files', 'productivity'],
    status: 'released',
    featured: true,
    tagline: 'Sort a messy folder, find exact duplicates, preview the plan, and keep an undo path.',
    description: 'A local Windows file organiser with type/date sorting, hash-based duplicate detection, complete previews, and undo for the last operation.',
    intro: 'Batch File Organiser gives high-trust folder work a visible safety rail. Scan first, inspect the proposed result, apply only when it makes sense, and undo the last run if the structure was not what you expected.',
    logo: '/Logos/BFO.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9PB3Q7K9FVZQ',
    docsUrl: 'https://3thousand30.github.io/batchfileorganiser-docs/',
    privacyLabel: 'Fully local',
    privacyText: 'Folder scanning, duplicate hashing, previews, file operations, and undo information stay on your Windows machine. No account or telemetry is required.',
    features: ['Organise files by type or date', 'Find exact duplicates by file hash', 'Preview the full proposed operation', 'Apply changes only after review', 'Undo the most recent operation', 'Run without uploading folder contents'],
    audiences: ['People cleaning a Downloads folder', 'Creators preparing a large project archive', 'Anyone who wants previews before bulk file moves'],
    screenshotItems: screenshots('bfo', [
      ['1.webp', 'Batch File Organiser folder scan', 'Scan the folder before deciding what to change.'],
      ['2.webp', 'Batch File Organiser preview', 'Inspect the complete organisation plan.'],
      ['3.webp', 'Batch File Organiser duplicate results', 'Find exact duplicate content even when names differ.'],
      ['6.webp', 'Batch File Organiser completed operation', 'Apply locally and retain an undo path.']
    ]),
    faq: [
      { q: 'How does duplicate detection work?', a: 'It compares file hashes, so exact copies can be found even when their filenames are different.' },
      { q: 'Can I preview changes?', a: 'Yes. The app shows the proposed plan before the file operation is applied.' },
      { q: 'Is it fully local?', a: 'Yes. Folder data and operations stay on the machine.' }
    ],
    relatedProducts: ['BCI', 'BRI', 'BEI'],
    relatedUseCases: ['find-exact-duplicate-files-by-hash', 'organise-and-prepare-a-working-file-collection'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BEI',
    slug: 'batchenhance-image',
    url: '/batchenhance-image.html',
    name: 'Batch Enhance Image',
    seoTitle: 'Batch Enhance Image — Batch Image Upscaler for Windows | 3thousand30',
    shortName: 'Batch Enhance Image',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['images', 'printing'],
    status: 'released',
    featured: false,
    tagline: 'Upscale selected images in batches for books, posters, prints, and physical products.',
    description: 'A fully local Windows image upscaler with batch processing, print-ready DPI controls, sharpening, and up to 8× scaling.',
    intro: 'Batch Enhance Image helps after selection, when the strongest image is compositionally right but too small for the planned print size. It processes a folder locally and gives you consistent output settings across the set.',
    logo: '/Logos/BEI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9n2vhg38ss00',
    docsUrl: 'https://3thousand30.github.io/batchenhanceimage-docs/',
    privacyLabel: 'Fully local',
    privacyText: 'Upscaling, sharpening, DPI settings, and exported files stay on your Windows machine with no cloud upload, account, or telemetry.',
    features: ['Upscale complete folders in one run', 'Choose scaling up to 8×', 'Set print-oriented DPI metadata', 'Apply sharpening when appropriate', 'Preview and review before final use', 'Process images without cloud upload'],
    audiences: ['Authors preparing book artwork', 'Artists making posters or prints', 'Sellers preparing images for physical products'],
    screenshotItems: screenshots('bei', [
      ['1.webp', 'Batch Enhance Image source selection', 'Choose the selected image folder.'],
      ['2.webp', 'Batch Enhance Image upscale controls', 'Set scale and print-oriented options consistently.'],
      ['4.webp', 'Batch Enhance Image comparison view', 'Inspect the result rather than assuming enlargement fixed everything.'],
      ['5.webp', 'Batch Enhance Image batch output', 'Export the prepared image set locally.']
    ]),
    faq: [
      { q: 'Can enhancement repair every bad image?', a: 'No. It can improve size and presentation, but it cannot rescue weak composition, severe artifacts, or missing detail.' },
      { q: 'Is it only for AI images?', a: 'No. It can prepare ordinary photos and digital artwork as well.' },
      { q: 'Does it upload images?', a: 'No. Processing is local.' }
    ],
    relatedProducts: ['BGI', 'BRI', 'BTP'],
    relatedUseCases: ['upscale-a-folder-of-images-offline', 'enhance-images-for-printing', 'create-a-photobook-with-ai-for-gifting', 'create-posters-to-print-or-sell'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BRI',
    slug: 'batchresize-image',
    url: '/batchresize-image.html',
    name: 'Batch Resize Image',
    seoTitle: 'Batch Resize Image — Batch Image Resizer for Windows | 3thousand30',
    shortName: 'Batch Resize Image',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['images', 'social', 'web'],
    status: 'released',
    featured: false,
    tagline: 'Turn one approved image set into the dimensions each channel needs.',
    description: 'A local Windows batch image resizer with platform presets, crop controls, live preview, and predictable folder output.',
    intro: 'Batch Resize Image handles the repetitive versioning step after the creative work is approved. Choose a target size or preset, check the crop, and process the set locally instead of resizing each file by hand.',
    logo: '/Logos/BRI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9PPKDVXPTLV0',
    docsUrl: 'https://3thousand30.github.io/batchresizeimage-docs/',
    privacyLabel: 'Fully local',
    privacyText: 'Source images, crop choices, resize settings, and outputs remain on the machine. No account, upload, or telemetry is required.',
    features: ['Resize a whole folder in one run', 'Use practical social, web, email, and marketplace presets', 'Control crop and aspect-ratio handling', 'Preview the result before processing', 'Keep source files separate from outputs', 'Work without a cloud upload'],
    audiences: ['Social teams preparing channel variants', 'Ecommerce sellers standardising listing images', 'Anyone maintaining web and email image sizes'],
    screenshotItems: screenshots('bri', [
      ['1.webp', 'Batch Resize Image folder setup', 'Choose the approved source set.'],
      ['2.webp', 'Batch Resize Image preset controls', 'Apply one repeatable target size.'],
      ['4.webp', 'Batch Resize Image crop preview', 'Check what will be kept before processing.'],
      ['5.webp', 'Batch Resize Image completed batch', 'Export a clean platform-ready folder.']
    ]),
    faq: [
      { q: 'Will every aspect ratio crop cleanly?', a: 'No. Review the preview, especially when faces, text, or products sit close to an edge.' },
      { q: 'Does it change the originals?', a: 'Use a separate output folder so the approved source set remains intact.' },
      { q: 'Does it need internet access?', a: 'No. Resizing is local.' }
    ],
    relatedProducts: ['BGI', 'BCI', 'BWI'],
    relatedUseCases: ['resize-hundreds-of-images-at-once', 'batch-crop-product-images-into-squares', 'resize-images-for-different-social-platforms', 'mass-create-social-media-content', 'batch-create-images-for-social-media'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BWI',
    slug: 'batchwatermark-image',
    url: '/batchwatermark-image.html',
    name: 'Batch Watermark Image',
    seoTitle: 'Batch Watermark Image — Batch Image Watermarker for Windows | 3thousand30',
    shortName: 'Batch Watermark Image',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['images', 'social', 'rights'],
    status: 'released',
    featured: false,
    tagline: 'Apply text, a logo, or both across an image set after reviewing the placement.',
    description: 'A fully local Windows batch watermarker with text and logo layers, opacity, placement, tiling, preview, and controlled export.',
    intro: 'Batch Watermark Image is for proof sets, branded previews, and visible rights notices. Configure the mark once, inspect representative images, and export a separate sharing set without modifying the masters.',
    logo: '/Logos/BWI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9n3s7zrpxgph',
    docsUrl: 'https://3thousand30.github.io/batchwatermarkimage-docs/',
    privacyLabel: 'Fully local',
    privacyText: 'Source images, watermark assets, preview states, and exported files stay on your machine with no cloud upload, account, or telemetry.',
    features: ['Add a text watermark, logo watermark, or both', 'Control position, opacity, scale, and tiling', 'Preview placement before the batch run', 'Create proof, branded, or rights-marked sets', 'Write results to a separate output folder', 'Process the full set locally'],
    audiences: ['Photographers sending client proofs', 'Creators sharing work before approval', 'Sellers adding a consistent visible brand or copyright line'],
    screenshotItems: screenshots('bwi', [
      ['1.webp', 'Batch Watermark Image source and watermark setup', 'Choose the source folder and visible mark.'],
      ['2.webp', 'Batch Watermark Image placement controls', 'Set position, opacity, and scale once.'],
      ['3.webp', 'Batch Watermark Image preview', 'Check legibility across representative images.'],
      ['4.webp', 'Batch Watermark Image batch result', 'Export the sharing copies locally.']
    ]),
    faq: [
      { q: 'Is a watermark a complete copyright-protection system?', a: 'No. It is a visible notice or sharing deterrent, not a guarantee against copying.' },
      { q: 'Can I keep clean masters?', a: 'Yes. Export watermarked copies to a separate folder and retain the original files.' },
      { q: 'Are images uploaded?', a: 'No. Watermarking is local.' }
    ],
    relatedProducts: ['BGI', 'BRI', 'BCI'],
    relatedUseCases: ['add-a-logo-watermark-to-a-folder-of-images', 'add-watermarks-before-sharing-images', 'add-copyright-information-to-images', 'mass-create-social-media-content'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BCI',
    slug: 'batchcompress-image',
    url: '/batchcompress-image.html',
    name: 'Batch Compress Image',
    seoTitle: 'Batch Compress Image — Batch Image Compressor for Windows | 3thousand30',
    shortName: 'Batch Compress Image',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['images', 'web', 'storage'],
    status: 'released',
    featured: false,
    tagline: 'Reduce a folder’s image weight for web, email, storage, and delivery.',
    description: 'A fully local Windows batch image compressor with quality controls, before-and-after comparison, and clean output folders.',
    intro: 'Batch Compress Image makes size reduction a controlled batch step. Keep the original exports, test a representative quality setting, compare the result, then process the delivery or archive copies locally.',
    logo: '/Logos/BCI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9n1dbc2g87ht',
    docsUrl: 'https://3thousand30.github.io/batchcompressimage-docs/',
    privacyLabel: 'Fully local',
    privacyText: 'Compression and comparison happen on the PC. Source images and output files are not uploaded to a cloud service.',
    features: ['Compress a complete image folder', 'Choose a quality target for the batch', 'Compare original and compressed output', 'Prepare lighter files for websites, email, and marketplaces', 'Keep source and compressed copies separate', 'Run without an account or upload'],
    audiences: ['Website owners improving page weight', 'Creators preparing email-friendly image sets', 'People reducing an archive or backup footprint'],
    screenshotItems: screenshots('bci', [
      ['1.webp', 'Batch Compress Image folder and quality setup', 'Choose a source set and initial quality target.'],
      ['2.webp', 'Batch Compress Image before and after comparison', 'Inspect visual quality before using the setting broadly.'],
      ['3.webp', 'Batch Compress Image completed results', 'Review the size reduction and exported folder.']
    ]),
    faq: [
      { q: 'Will compression always look identical?', a: 'No. Strong compression can introduce visible artifacts, so compare representative images before processing the whole set.' },
      { q: 'Should I replace the original files?', a: 'Keep the masters and create a separate delivery or archive copy unless you are certain the reduced files are sufficient.' },
      { q: 'Is it local?', a: 'Yes. No image upload is required.' }
    ],
    relatedProducts: ['BRI', 'BWI', 'BFO'],
    relatedUseCases: ['compress-images-to-save-storage-space', 'organise-and-prepare-a-working-file-collection'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BMP',
    slug: 'batch-merge-pdfs',
    url: '/batch-merge-pdfs.html',
    name: 'Batch Merge PDFs',
    seoTitle: 'Batch Merge PDFs — Offline PDF Merger for Windows | 3thousand30',
    shortName: 'Batch Merge PDFs',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'files', 'publishing'],
    status: 'released',
    featured: true,
    tagline: 'Combine a folder of PDFs into one ordered file without uploading the documents.',
    description: 'A lightweight local PDF merger for Windows with alphabetical ordering, folder-based output naming, optional page numbers, progress, and skip-existing support.',
    intro: 'Batch Merge PDFs turns a correctly named folder into one final PDF. It combines files in alphabetical filename order, can add fresh continuous page numbers, and keeps the full job on the PC.',
    logo: '/Logos/BMP.png',
    storeUrl: 'https://apps.microsoft.com/detail/9NVDT0TTN0WH',
    docsUrl: 'https://3thousand30.github.io/batchmergepdf-docs/',
    privacyLabel: 'Fully local',
    privacyText: 'The source PDFs and merged result remain on your Windows machine. No account, subscription, or cloud upload by 3thousand30 is required.',
    features: ['Merge every PDF directly inside one folder', 'Use alphabetical filenames to control the order', 'Name the result after the source folder', 'Add continuous page numbers when useful', 'Skip an output that already exists', 'Track progress and open the output folder after completion'],
    audiences: ['People assembling chapters or exported sections', 'Teams combining reports, invoices, scans, or worksheets', 'Anyone avoiding online PDF-upload services'],
    screenshotItems: screenshots('bmp', [
      ['01-main-merge.png', 'Batch Merge PDFs folder and output setup', 'Choose the PDF folder, output location, and page-number option.'],
      ['02-merge-complete.png', 'Completed local merge in Batch Merge PDFs', 'Review the completed merge and open the output folder.'],
      ['03-getting-started.png', 'Batch Merge PDFs getting-started guidance', 'Use predictable filenames to control the final document order.']
    ]),
    faq: [
      { q: 'How is the merge order decided?', a: 'PDFs are merged in alphabetical filename order. Numbered prefixes such as 01, 02, and 03 make the intended order explicit.' },
      { q: 'Can it add page numbers?', a: 'Yes. You can add fresh continuous page numbers across the merged output.' },
      { q: 'Are PDFs uploaded?', a: 'No. The merge runs locally.' }
    ],
    relatedProducts: ['BSP', 'BTP', 'BT'],
    relatedUseCases: ['combine-markdown-chapters-into-one-book-pdf', 'merge-pdfs-without-using-the-internet', 'create-a-poetry-book', 'translate-a-book-for-new-markets'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BSP',
    slug: 'batch-split-pdfs',
    url: '/batch-split-pdfs.html',
    name: 'Batch Split PDFs',
    seoTitle: 'Batch Split PDFs — Offline PDF Splitter for Windows | 3thousand30',
    shortName: 'Batch Split PDFs',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'files', 'productivity'],
    status: 'released',
    featured: false,
    tagline: 'Split one PDF or a whole folder into pages or fixed-size chunks locally.',
    description: 'A lightweight PDF splitter for Windows with single-file and folder modes, optional subfolder scanning, pages-per-file control, and predictable output names.',
    intro: 'Batch Split PDFs handles both the one-document job and the folder-wide job. Choose one page per output or a fixed number of pages per chunk, then follow the local batch without opening each PDF individually.',
    logo: '/Logos/BSP.png',
    storeUrl: 'https://apps.microsoft.com/detail/9MZKRHK6NRRS',
    docsUrl: 'https://3thousand30.github.io/batchsplitpdf-docs/',
    privacyLabel: 'Fully local',
    privacyText: 'PDF reading, splitting, and file output happen locally on Windows. No account, subscription, or cloud upload by 3thousand30 is required.',
    features: ['Split one PDF into individual pages', 'Split one PDF into fixed-size chunks', 'Process all PDFs in a folder', 'Optionally include nested subfolders', 'Use automatic numbered output names', 'Track progress and safely skip existing outputs'],
    audiences: ['People extracting pages for review or upload', 'Teams breaking reports or scans into smaller packets', 'Publishers separating combined documents before a new workflow'],
    screenshotItems: screenshots('bsp', [
      ['01-single-pdf-split.png', 'Single-file setup in Batch Split PDFs', 'Split one PDF into individual pages or fixed-size chunks.'],
      ['02-folder-split-complete.png', 'Completed folder batch in Batch Split PDFs', 'Process a whole folder and review the completed outputs.']
    ]),
    faq: [
      { q: 'Can it create one file per page?', a: 'Yes. Set pages per file to 1.' },
      { q: 'Can it process subfolders?', a: 'Yes. Folder mode can optionally include PDFs inside nested folders.' },
      { q: 'Does splitting use the cloud?', a: 'No. The workflow is local.' }
    ],
    relatedProducts: ['BMP', 'BTP', 'BFO'],
    relatedUseCases: ['split-multiple-pdfs-into-separate-pages', 'translate-a-book-for-new-markets', 'create-short-stories-for-teaching'],
    lastmod: '2026-08-08'
  },
  {
    code: 'BTP',
    slug: 'batch-text-to-pdf',
    url: '/batch-text-to-pdf.html',
    name: 'Batch Text to PDF',
    seoTitle: 'Batch Text to PDF — Batch PDF Creator for Windows | 3thousand30',
    shortName: 'Batch Text to PDF',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'publishing', 'files'],
    status: 'released',
    featured: true,
    tagline: 'Turn folders of Markdown, text, DOCX, and images into separate or combined PDFs.',
    description: 'A local Windows batch PDF maker with flexible page sizes, Markdown rendering, multilingual colour emoji, image pairing, text-over-background pages, combined output, and page numbering.',
    intro: 'Batch Text to PDF converts a mixed folder into finished PDFs in one run. Create one PDF per source or a single ordered document, pair same-named text and images inline, on separate pages, or with the image behind the text as a full-page background, and keep the conversion local.',
    logo: '/Logos/BTP.png',
    storeUrl: 'https://apps.microsoft.com/detail/9NS1L0DK0FQL',
    docsUrl: 'https://3thousand30.github.io/batchtexttopdf-docs/',
    privacyLabel: 'Fully local',
    privacyText: 'Core conversion runs on your PC. No account, upload, AI service, analytics, or telemetry is required.',
    features: ['Convert Markdown, TXT, DOCX, JPG, PNG, WebP, and GIF sources', 'Create one PDF per source or one combined ordered PDF', 'Choose eight presets or custom page dimensions and margins', 'Add page numbers to individual or combined output', 'Auto-pair same-named text and images inline, on separate pages, or as full-page backgrounds', 'Preserve multilingual text and full-colour emoji'],
    audiences: ['Writers converting chapters or guides', 'Teachers creating worksheet and story packs', 'Publishers assembling illustrated drafts and small books'],
    screenshotItems: screenshots('btp', [
      ['1. Convert whole folders at once.png', 'Batch Text to PDF ready to convert a folder containing Markdown, text, DOCX, and image files', 'Convert whole folders at once.'],
      ['2. Control every page dimension.png', 'Custom page width, height, and margins in Batch Text to PDF', 'Control every page dimension.'],
      ['3. Place text over images.png', 'Background image pairing selected in Batch Text to PDF for text over full-page images', 'Place text over images.'],
      ['4. Build one ordered PDF.png', 'Combined PDF mode with US Trade size and page numbering in Batch Text to PDF', 'Build one ordered PDF.'],
      ['5. See every conversion result.png', 'Completed Batch Text to PDF run showing four converted source files', 'See every conversion result.'],
      ['6. Keep files on your device.png', 'Batch Text to PDF privacy information explaining that document conversion stays on the device', 'Keep files on your device.']
    ]),
    faq: [
      { q: 'Which source formats are supported?', a: 'Markdown, plain text, DOCX, JPG, JPEG, PNG, WebP, and GIF. Existing PDFs are skipped rather than reconverted.' },
      { q: 'Does DOCX preserve the original Word layout?', a: 'No. It extracts paragraph text; original styling, embedded images, and page layout are not reproduced.' },
      { q: 'Can it combine a whole folder?', a: 'Yes. Combined mode processes supported files in filename order and can add page numbers.' },
      { q: 'Does it need an AI service?', a: 'No. PDF conversion is local and does not require an AI provider.' }
    ],
    relatedProducts: ['BMP', 'BSP', 'BGT'],
    relatedUseCases: ['convert-markdown-files-to-pdf-in-bulk', 'combine-markdown-chapters-into-one-book-pdf', 'batch-create-pdfs-from-text', 'create-a-colouring-book-for-children', 'create-a-poetry-book', 'create-short-stories-for-teaching'],
    lastmod: '2026-08-09'
  },
  {
    code: 'BCP',
    slug: 'batch-compress-pdf',
    url: '/batch-compress-pdf.html',
    name: 'Batch Compress PDF',
    seoTitle: 'Batch Compress PDF — Private Offline PDF Compressor for Windows | 3thousand30',
    shortName: 'Batch Compress PDF',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'files', 'productivity'],
    status: 'released',
    featured: true,
    tagline: 'Make batches of PDFs smaller on your PC without uploading them.',
    description: 'A local Windows PDF compressor with Flatten for strong size reduction, Smart for structure-preserving compression, validated outputs, and a no-bloat guarantee.',
    intro: 'Batch Compress PDF reduces document sets locally. Flatten works best for most size-reduction jobs, especially scanned or image-heavy PDFs, by creating page-image copies. Smart is available when selectable text, links, forms, annotations, and PDF structure need to remain intact. Encrypted and signed files are skipped, inputs are never overwritten, and a larger candidate is never retained.',
    logo: '/Logos/BCP.png',
    storeId: '9NNPJR6NP2S3',
    storeIdentity: '3thousand30.BatchCompressPDFs',
    storeUrl: 'https://apps.microsoft.com/detail/9NNPJR6NP2S3',
    docsUrl: 'https://3thousand30.github.io/batchcompresspdfs-docs/',
    privacyLabel: 'Fully local · no upload',
    privacyText: 'PDF contents remain on the PC. No account, document upload, advertising SDK, or product analytics is required for compression.',
    features: ['Compress individual PDFs, selections, or folders', 'Use Flatten for strong reduction on scanned or image-heavy PDFs', 'Use Smart when text, links, forms, annotations, and PDF structure must remain intact', 'See clear warnings before creating page-image copies', 'Compare Original, Processed, and Split previews', 'Keep inputs safe with validation, temporary outputs, and collision-safe names'],
    audiences: ['People reducing private PDFs before email or archive storage', 'Teams handling scan-heavy local document sets', 'Anyone avoiding browser-based PDF uploads'],
    screenshotItems: screenshots('bcp', [
      ['1. Smart preserves PDF structure.png', 'Batch Compress PDF Smart mode with structure-preserving preview navigation', 'Smart preserves PDF structure.'],
      ['2. Flatten compression preview.png', 'Batch Compress PDF Flatten mode with Split preview and structure warning', 'Flatten compression preview.'],
      ['3. Compress PDFs locally.png', 'Batch Compress PDF local compression progress with Cancel action', 'Compress PDFs locally.'],
      ['4. Review compression savings.png', 'Batch Compress PDF completed result with KB and percentage saved', 'Review compression savings.']
    ]),
    faq: [
      { q: 'Are my PDFs uploaded?', a: 'No. Compression and preview rendering run locally on the Windows PC.' },
      { q: 'What is Flatten?', a: 'Flatten renders pages into page images. It is separate because selectable text, links, forms, tags, and signatures are not retained.' },
      { q: 'Can compression make a file larger?', a: 'The app validates candidates and keeps the original bytes whenever an optimised candidate would be larger.' }
    ],
    relatedProducts: ['BWP', 'BPP', 'BSP'],
    relatedUseCases: ['compress-pdfs-without-uploading-them', 'reduce-scanned-pdfs-for-email-and-archiving'],
    lastmod: '2026-08-10'
  },
  {
    code: 'BWP',
    slug: 'batch-watermark-pdfs',
    url: '/batch-watermark-pdfs.html',
    name: 'Batch Watermark PDF',
    seoTitle: 'Batch Watermark PDF — Add Text and Logo Marks Locally | 3thousand30',
    shortName: 'Batch Watermark PDF',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'files', 'productivity'],
    status: 'released',
    featured: true,
    tagline: 'Add text, logo, or combined watermarks to PDF batches locally, with precise placement and a live preview.',
    description: 'A local Windows batch watermarker for text, PNG, JPEG, combined marks, placement, opacity, rotation, edge margin, tiling, page ranges, and layering.',
    intro: 'Batch Watermark PDF applies text, PNG, JPEG, or combined marks without turning ordinary outputs into page screenshots. Choose placement, rotation, opacity, edge margin, text colour, tiling, page ranges, and above- or below-content layering, then check the result in a live Original, Watermarked, or Split preview before running the batch.',
    logo: '/Logos/BWP.png',
    storeId: '9N5C4HHWCR6R',
    storeIdentity: '3thousand30.BatchWatermarkPDFs',
    storeUrl: 'https://apps.microsoft.com/detail/9N5C4HHWCR6R',
    docsUrl: 'https://3thousand30.github.io/batchwatermarkpdfs-docs/',
    privacyLabel: 'Fully local · clean masters stay clean',
    privacyText: 'PDFs and watermark image files stay on the PC. Outputs are separate validated copies, so approved clean masters remain unchanged.',
    features: ['Use text, PNG, JPEG, or combined watermarks', 'Choose nine placements, rotation, opacity, and edge margin', 'Set watermark text colour, size, and wording per batch', 'Repeat marks in an adjustable tile pattern, or target precise page ranges', 'Place marks above or below existing page content', 'Check results in a live Original, Watermarked, or Split preview'],
    audiences: ['Teams marking drafts and proofs before sharing', 'People applying a logo across document sets', 'Anyone who needs consistent PDF status marks without an upload'],
    screenshotItems: screenshots('bwp', [
      ['1. Watermark PDF batches locally.png', 'Text watermark and live preview controls in Batch Watermark PDF', 'Preview text watermarks before processing the full PDF batch.'],
      ['2. Add image watermarks precisely.png', 'Image watermark scale and placement controls in Batch Watermark PDF', 'Add logo watermarks with precise scale and placement control.'],
      ['3. Review every processing result.png', 'Generation log showing success, skip, and warning results in Batch Watermark PDF', 'Review every success, skip, warning, and processing error.'],
      ['4. Preview and finish every batch.png', 'Completed batch with output folder access in Batch Watermark PDF', 'Finish the batch and open your validated PDF outputs.']
    ]),
    faq: [
      { q: 'Which image formats are supported?', a: 'Version 1.0 supports PNG, JPG, and JPEG. SVG input is deferred.' },
      { q: 'Does watermarking flatten the PDF?', a: 'No. The normal workflow adds page resources and content while preserving text, links, forms, annotations, and page geometry.' },
      { q: 'Does a watermark prevent copying?', a: 'No. A watermark communicates ownership or status and discourages misuse, but it is not encryption or DRM.' }
    ],
    relatedProducts: ['BCP', 'BPP', 'BWI'],
    relatedUseCases: ['add-watermarks-to-pdf-documents-in-batches', 'watermark-client-pdf-proofs-before-sharing'],
    lastmod: '2026-08-14'
  },
  {
    code: 'BPP',
    slug: 'batch-protect-pdfs',
    url: '/batch-protect-pdfs.html',
    name: 'Batch Protect PDF',
    seoTitle: 'Batch Protect PDF — AES-256 PDF Password Protection for Windows | 3thousand30',
    shortName: 'Batch Protect PDF',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'files', 'productivity'],
    status: 'released',
    featured: true,
    tagline: 'Password-protect PDF batches with AES-256, or remove that protection again — entirely locally.',
    description: 'A local Windows batch PDF protector: one password locks a batch of PDFs with AES-256 so nobody without it can open the content, and Unprotect mode removes that protection again given the password.',
    intro: 'Batch Protect PDF locks a folder of PDFs with AES-256 encryption — without the password, nobody can open them. Set one password, confirm it, and optionally encrypt metadata too. Switch to Unprotect mode to remove protection you already have the password for; a file that rejects it is skipped, not a reason to stop the batch.',
    logo: '/Logos/BPP.png',
    storeId: '9N16J4D2MDM1',
    storeIdentity: '3thousand30.BatchProtectPDFs',
    storeUrl: 'https://apps.microsoft.com/detail/9N16J4D2MDM1',
    docsUrl: 'https://3thousand30.github.io/batchprotectpdfs-docs/',
    privacyLabel: 'Local encryption · transient passwords',
    privacyText: 'PDFs and passwords stay on the device. Passwords are not written to settings or logs and are cleared where the platform and encryption library permit.',
    features: ['Encrypt PDF strings and streams with AES-256', 'One password, confirmed, locks the whole batch', 'Generate a strong password securely', 'Optionally encrypt document metadata too', 'Unprotect mode removes existing protection given the password', 'Wrong-password files are skipped, not batch-aborting'],
    audiences: ['People sending confidential PDF deliverables', 'Teams who need a batch of PDFs genuinely unreadable without a shared password', 'Anyone protecting or unprotecting document batches without a web upload'],
    screenshotItems: screenshots('bpp', [
      ['1. Protect all your PDFs at once.png', 'Batch Protect PDF preflight list and input folder', 'Protect all your PDFs at once.'],
      ['2. Generate a secure password when needed.png', 'Secure password generation in Batch Protect PDF', 'Generate a secure password when needed.'],
      ['3. Unprotect PDFs in batches.png', 'Unprotect mode in Batch Protect PDF', 'Unprotect PDFs in batches.'],
      ['4. Review every processing result.png', 'Completed and verified Batch Protect PDF results', 'Review every processing result.']
    ]),
    faq: [
      { q: 'What encryption does the app use?', a: 'It creates AES-256 PDF encryption using the modern V5/revision 6 security handler.' },
      { q: 'Why only one password instead of separate open and owner passwords?', a: 'Because the point is content nobody without the password can read — splitting that into a permissions layer a viewer can just ignore was never real protection.' },
      { q: 'What happens to a file with the wrong password during Unprotect?', a: 'It is skipped, not treated as a reason to stop — the rest of the batch keeps going.' }
    ],
    relatedProducts: ['BCP', 'BWP', 'BSP'],
    relatedUseCases: ['protect-pdf-deliverables-with-passwords'],
    lastmod: '2026-08-14'
  },
  {
    code: 'KR',
    slug: 'key-rush',
    url: '/key-rush.html',
    name: 'Key Rush',
    seoTitle: 'Key Rush — Offline Typing Game for Windows | 3thousand30',
    shortName: 'Key Rush',
    type: 'game',
    typeLabel: 'Offline game',
    categories: ['game', 'typing', 'arcade', 'offline'],
    status: 'released',
    featured: true,
    tagline: 'A Windows typing game staged like a live breach console.',
    description: 'Offline-first typing action with story missions, an accelerating endless lane, no-fail zen practice, local top-10 boards, and no account or telemetry.',
    intro: 'Key Rush makes typing practice feel like a system under pressure. Clear three hacker-thriller story missions, chase a score as Endless accelerates, or stay in rhythm in Zen without a fail state.',
    logo: '/Logos/KR.png',
    storeUrl: 'https://apps.microsoft.com/detail/9MW7722B1026',
    docsUrl: 'https://3thousand30.github.io/keyrush-docs/',
    privacyLabel: 'Offline-first · local scores',
    privacyText: 'Play, settings, local top-10 boards, score tags, and saved result cards stay on the machine. No account or telemetry is required.',
    features: ['Play Story, Endless, or Zen modes', 'Clear nine levels across three story chapters', 'Survive an endless lane that speeds up over time', 'Practise in a no-fail Zen passage mode', 'Keep local top-10 boards for every mode', 'Adjust motion, font size, contrast, sound, and music'],
    audiences: ['Players who want a stylish typing game', 'People practising accuracy without an account', 'Score chasers sharing one local Windows PC'],
    screenshotItems: screenshots('kr', [
      ['02-home-menu.png', 'Key Rush terminal-style main menu', 'Choose Story, Endless, or Zen.'],
      ['03-chapter-select.png', 'Key Rush story chapter selection', 'Run three hacker-thriller story missions.'],
      ['08-story-gameplay.png', 'Typing action during a Key Rush story mission', 'Type through the live breach console.'],
      ['11-endless-life-bonus.png', 'Key Rush endless mode under pressure', 'Chase the local board as the lane accelerates.'],
      ['09-zen-gameplay.png', 'Key Rush no-fail Zen typing mode', 'Practise rhythm and accuracy without a fail state.'],
      ['04-leaderboard.png', 'Key Rush local top-ten leaderboard', 'Keep score chasing local to the machine.']
    ]),
    faq: [
      { q: 'Can I play offline?', a: 'Yes. The core game is offline-first.' },
      { q: 'Does it require an account?', a: 'No. Scores and settings are stored locally.' },
      { q: 'Is Zen mode timed?', a: 'Zen is designed as a no-fail practice lane so you can focus on rhythm and accuracy rather than losing a run.' }
    ],
    relatedProducts: ['BGT', 'BFO'],
    relatedUseCases: [],
    lastmod: '2026-08-08'
  },
  {
    code: 'CWAI',
    slug: 'chess-with-any-ai',
    url: '/chess-with-any-ai.html',
    name: 'Chess with any AI',
    seoTitle: 'Chess with any AI — Play AI Chess on Windows | 3thousand30',
    shortName: 'Chess with any AI',
    type: 'game',
    typeLabel: 'AI chess game',
    categories: ['game', 'board', 'strategy', 'ai'],
    status: 'released',
    featured: true,
    tagline: 'A private desktop chessboard for human duels, model trials, and beautiful game review.',
    description: 'Play chess on Windows against one AI profile, watch two AI profiles play, or keep a local human match archive with replay and shareable result cards.',
    intro: 'Chess with any AI is a focused desktop board for people who want to play people or their own AI profiles without handing their game history to another platform. Add AI profiles from the providers you already use, choose the matchup and clock, then replay, export, or share the finished game.',
    logo: '/Logos/CWAI.png',
    storeId: '9PG2KT0L8FQS',
    storeIdentity: '3thousand30.ChesswithanyAI',
    storeUrl: 'https://apps.microsoft.com/detail/9PG2KT0L8FQS',
    docsUrl: 'https://3thousand30.github.io/chesswithanyAI-docs/',
    privacyLabel: 'Local profiles · bring your own AI key',
    privacyText: 'Human profiles, saved games, board settings, and result cards stay on the PC. AI keys are protected locally; when an AI seat plays, the board request is sent only to the provider you selected.',
    features: [
      'Play human vs human, human vs AI, or AI vs AI',
      'Save AI profiles for compatible providers and models',
      'Validate every AI move against the local chess rules',
      'Choose untimed, 10-minute, 5-minute, or 3 + 2 clocks',
      'Replay saved games move by move, with keyboard controls',
      'Export the moves or share a board-aware result card'
    ],
    audiences: [
      'Chess players who want to test their own AI profiles at the board',
      'Friends sharing a local human match without an account',
      'People who want to preserve, replay, and share games from one desktop app'
    ],
    screenshotItems: screenshots('cwai', [
      ['01-home-new-game.webp', 'Chess with any AI home screen with a Persian-inspired chess scene', 'Start a board, browse saved games, or change the experience.'],
      ['02-match-setup-human-v-ai.webp', 'Match setup for a human versus AI game in Chess with any AI', 'Choose the matchup, seats, profiles, and clock before the first move.'],
      ['03-live-human-v-ai.webp', 'Live Chess with any AI board during a human versus AI game', 'Keep both players, clocks, and the game state clear around the board.'],
      ['04-game-complete-share.webp', 'Chess with any AI game completion screen with a shareable result card', 'Review the result, replay the game, or save a board-aware share card.']
    ]),
    faq: [
      { q: 'Does the app include AI usage?', a: 'No. Add an AI profile with a provider and model you already use. You pay that provider directly for any AI usage.' },
      { q: 'Can I play without an AI key?', a: 'Yes. Human versus human games do not need a provider or an API key.' },
      { q: 'Are AI moves trusted blindly?', a: 'No. The app checks AI moves against its local chess rules before applying them to the board.' }
    ],
    relatedProducts: ['KR', 'BGT'],
    relatedUseCases: [],
    lastmod: '2026-08-27'
  }
];

module.exports = products.map((product) => ({
  ...product,
  price: {
    ...usdPrices[product.code],
    currency: 'USD',
    region: 'US',
    verifiedOn: '2026-08-08'
  }
}));
