function screenshots(folder, files) {
  return files.map(([file, alt, caption]) => ({
    src: `/screenshots/${folder}/${file}`,
    alt,
    caption
  }));
}

module.exports = [
  {
    code: 'BGT',
    slug: 'batchgen-text',
    url: '/batchgen-text.html',
    name: 'Batch Generate Text with any AI',
    seoTitle: 'Batch Generate Text with any AI — Batch AI Writer for Windows | 3thousand30',
    shortName: 'Batch Generate Text',
    type: 'ai',
    typeLabel: 'AI creation',
    categories: ['writing', 'publishing', 'social'],
    status: 'released',
    featured: true,
    tagline: 'Turn a topic list into a reviewed batch of writing with your own AI provider.',
    description: 'Bulk AI writing for Windows with reusable personas, sample analysis, CSV topic lists, multiple providers, and local Markdown or text outputs.',
    intro: 'Batch Generate Text is built for writing jobs that repeat: social posts, article drafts, product copy, poems, stories, and custom formats. Set the structure once, preview one result, review the batch, and keep the saved files on your PC.',
    logo: '/Logos/BGT.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9n3b1b8dt39f',
    docsUrl: 'https://3thousand30.github.io/batchgentext-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price for your region.',
    privacyLabel: 'BYO key · local outputs',
    privacyText: 'API keys are encrypted locally with Windows DPAPI and finished files are saved to your PC. Prompts are sent only to the external AI provider you choose.',
    features: [
      'Generate complete batches from a CSV topic list',
      'Save multiple AI provider and model connections',
      'Use reusable personas and writing samples for consistency',
      'Create posts, threads, articles, product copy, and custom formats',
      'Preview before committing to a full batch',
      'Save finished work locally as Markdown or plain text'
    ],
    audiences: ['Creators building a repeatable content system', 'Publishers preparing stories, poems, or chapters', 'Small teams producing structured copy without another subscription'],
    screenshotItems: screenshots('bgt', [
      ['1.webp', 'Batch Generate Text topic and template setup', 'Choose the format and prepare the batch.'],
      ['2.webp', 'Provider and model selection in Batch Generate Text', 'Bring the provider and model that fit the job.'],
      ['3.webp', 'Persona controls for consistent batch writing', 'Reuse a voice and writing rules across the set.'],
      ['6.webp', 'Completed Batch Generate Text files saved locally', 'Review the completed run and keep the outputs locally.']
    ]),
    faq: [
      { q: 'Does it include AI usage?', a: 'No. You bring your own provider key and pay that provider directly, so you can choose the model and cost profile.' },
      { q: 'Where are outputs stored?', a: 'Generated Markdown or text files are saved to the folder you choose on your Windows PC.' },
      { q: 'Is the whole workflow offline?', a: 'The app and saved outputs are local. Generation requires a connection to the external AI provider you selected.' }
    ],
    relatedProducts: ['BGI', 'BT', 'BTP'],
    relatedUseCases: ['mass-create-social-media-content', 'create-short-stories-for-teaching', 'create-a-poetry-book', 'create-song-lyrics-for-inspiration'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BGI',
    slug: 'batchgen-image',
    url: '/batchgen-image.html',
    name: 'Batch Generate Image with any AI',
    seoTitle: 'Batch Generate Image with any AI — Bulk Image Generator for Windows | 3thousand30',
    shortName: 'Batch Generate Image with any AI',
    type: 'ai',
    typeLabel: 'AI creation',
    categories: ['images', 'publishing', 'social'],
    status: 'released',
    featured: true,
    tagline: 'Generate coherent image sets for campaigns, books, posters, and product ideas.',
    description: 'Bulk AI image generation on Windows with your own provider, reusable visual personas, styles, reference images, captions, and local outputs.',
    intro: 'Batch Generate Image with any AI is for projects that need an image set rather than one lucky prompt. Build the list, choose a visual direction, generate more than you need, and keep human selection at the centre of the workflow.',
    logo: '/Logos/BGI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9pfr4v6827xq',
    docsUrl: 'https://3thousand30.github.io/batchgenimage-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price for your region.',
    privacyLabel: 'BYO key · local outputs',
    privacyText: 'Your provider receives the generation request you choose to send. API keys are encrypted locally and generated images are saved on your machine rather than a 3thousand30 cloud.',
    features: [
      'Generate image batches from a prepared topic list',
      'Choose your own compatible provider and model',
      'Reuse visual personas, styles, and reference images',
      'Use templates for posters, covers, social posts, or custom ratios',
      'Add captions when image-and-text output is useful',
      'Keep every generated file in a local project folder'
    ],
    audiences: ['Creators planning visual series', 'Authors and publishers building illustrated artifacts', 'Sellers preparing posters, concepts, and campaign imagery'],
    screenshotItems: screenshots('bgi', [
      ['1.webp', 'Batch Generate Image with any AI project setup', 'Set up the image batch and output direction.'],
      ['2.webp', 'Batch Generate Image with any AI template and prompt controls', 'Choose a reusable format for the set.'],
      ['4.webp', 'Generated image batch review', 'Generate enough candidates to make a real selection.'],
      ['5.webp', 'Batch Generate Image with any AI local output view', 'Keep the selected image files on your PC.']
    ]),
    faq: [
      { q: 'Does it include image-generation credits?', a: 'No. You use your own provider key, choose the model, and pay the provider directly.' },
      { q: 'Can it keep a whole series consistent?', a: 'Visual personas, styles, references, and reusable templates help, but you should still generate alternatives and review the set carefully.' },
      { q: 'Where are the generated images saved?', a: 'The files are saved locally in the output folder you choose.' }
    ],
    relatedProducts: ['BGT', 'BEI', 'BRI'],
    relatedUseCases: ['create-a-photobook-with-ai-for-gifting', 'batch-create-images-for-social-media', 'create-a-colouring-book-for-children', 'create-posters-to-print-or-sell'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BT',
    slug: 'batchtranslate',
    url: '/batchtranslate.html',
    name: 'Batch Translate with AI',
    seoTitle: 'Batch Translate with AI — Document Translator for Windows | 3thousand30',
    shortName: 'Batch Translate',
    type: 'ai',
    typeLabel: 'AI translation',
    categories: ['translation', 'writing', 'publishing'],
    status: 'released',
    featured: true,
    tagline: 'Translate folders of documents into one or more languages with your own provider.',
    description: 'Batch-translate PDF, DOCX, TXT, and Markdown files on Windows using your own AI key and save each result locally.',
    intro: 'Batch Translate turns a folder of documents into a managed translation run. Choose the target languages, provider, and model, then review the saved results before they become public editions.',
    logo: '/Logos/BT.png',
    storeUrl: 'https://apps.microsoft.com/detail/9N75DWR9X2S7',
    docsUrl: 'https://3thousand30.github.io/batchtranslate-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price for your region.',
    privacyLabel: 'BYO key · local outputs',
    privacyText: 'Source content is sent to the external AI provider you select for translation. Keys are encrypted locally and the translated files are saved on your PC.',
    features: ['Process PDF, DOCX, TXT, and Markdown files', 'Translate a batch into one or more target languages', 'Choose your own provider and model', 'Save provider configurations for repeat work', 'Track progress across the folder', 'Store every translated result locally'],
    audiences: ['Independent publishers preparing new language editions', 'Teams localising document sets', 'Creators republishing finished content for another audience'],
    screenshotItems: screenshots('bt', [
      ['1.webp', 'Batch Translate document and language setup', 'Select the source folder and target languages.'],
      ['2.webp', 'AI provider controls in Batch Translate', 'Choose the provider and model for the run.'],
      ['3.webp', 'Batch translation progress view', 'Follow the document batch as it is translated.'],
      ['4.webp', 'Translated files saved from Batch Translate', 'Review the translated outputs locally.']
    ]),
    faq: [
      { q: 'Which files can it translate?', a: 'It supports PDF, DOCX, TXT, and Markdown sources stored in local folders.' },
      { q: 'Does translation still need review?', a: 'Yes. Names, tone, formatting, terminology, and culturally sensitive wording need human review before publication.' },
      { q: 'Does 3thousand30 store my documents?', a: 'No. The selected AI provider receives the translation request; 3thousand30 does not add another cloud-storage layer.' }
    ],
    relatedProducts: ['BGT', 'BTP', 'BMP'],
    relatedUseCases: ['publish-content-in-different-languages', 'translate-a-book-for-new-markets'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BFO',
    slug: 'batchfile-organiser',
    url: '/batchfile-organiser.html',
    name: 'BatchFile Organiser',
    seoTitle: 'BatchFile Organiser — File Organiser for Windows | 3thousand30',
    shortName: 'BatchFile Organiser',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['files', 'productivity'],
    status: 'released',
    featured: true,
    tagline: 'Sort a messy folder, find exact duplicates, preview the plan, and keep an undo path.',
    description: 'A local Windows file organiser with type/date sorting, hash-based duplicate detection, complete previews, and undo for the last operation.',
    intro: 'BatchFile Organiser gives high-trust folder work a visible safety rail. Scan first, inspect the proposed result, apply only when it makes sense, and undo the last run if the structure was not what you expected.',
    logo: '/Logos/BFO.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9PB3Q7K9FVZQ',
    docsUrl: 'https://3thousand30.github.io/batchfileorganiser-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price for your region.',
    privacyLabel: 'Fully local',
    privacyText: 'Folder scanning, duplicate hashing, previews, file operations, and undo information stay on your Windows machine. No account or telemetry is required.',
    features: ['Organise files by type or date', 'Find exact duplicates by file hash', 'Preview the full proposed operation', 'Apply changes only after review', 'Undo the most recent operation', 'Run without uploading folder contents'],
    audiences: ['People cleaning a Downloads folder', 'Creators preparing a large project archive', 'Anyone who wants previews before bulk file moves'],
    screenshotItems: screenshots('bfo', [
      ['1.webp', 'BatchFile Organiser folder scan', 'Scan the folder before deciding what to change.'],
      ['2.webp', 'BatchFile Organiser preview', 'Inspect the complete organisation plan.'],
      ['3.webp', 'BatchFile Organiser duplicate results', 'Find exact duplicate content even when names differ.'],
      ['6.webp', 'BatchFile Organiser completed operation', 'Apply locally and retain an undo path.']
    ]),
    faq: [
      { q: 'How does duplicate detection work?', a: 'It compares file hashes, so exact copies can be found even when their filenames are different.' },
      { q: 'Can I preview changes?', a: 'Yes. The app shows the proposed plan before the file operation is applied.' },
      { q: 'Is it fully local?', a: 'Yes. Folder data and operations stay on the machine.' }
    ],
    relatedProducts: ['BCI', 'BRI', 'BEI'],
    relatedUseCases: ['organise-and-prepare-a-working-file-collection'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BEI',
    slug: 'batchenhance-image',
    url: '/batchenhance-image.html',
    name: 'BatchEnhance Image',
    seoTitle: 'BatchEnhance Image — Batch Image Upscaler for Windows | 3thousand30',
    shortName: 'BatchEnhance Image',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['images', 'printing'],
    status: 'released',
    featured: false,
    tagline: 'Upscale selected images in batches for books, posters, prints, and physical products.',
    description: 'A fully local Windows image upscaler with batch processing, print-ready DPI controls, sharpening, and up to 8× scaling.',
    intro: 'BatchEnhance Image helps after selection, when the strongest image is compositionally right but too small for the planned print size. It processes a folder locally and gives you consistent output settings across the set.',
    logo: '/Logos/BEI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9n2vhg38ss00',
    docsUrl: 'https://3thousand30.github.io/batchenhanceimage-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price for your region.',
    privacyLabel: 'Fully local',
    privacyText: 'Upscaling, sharpening, DPI settings, and exported files stay on your Windows machine with no cloud upload, account, or telemetry.',
    features: ['Upscale complete folders in one run', 'Choose scaling up to 8×', 'Set print-oriented DPI metadata', 'Apply sharpening when appropriate', 'Preview and review before final use', 'Process images without cloud upload'],
    audiences: ['Authors preparing book artwork', 'Artists making posters or prints', 'Sellers preparing images for physical products'],
    screenshotItems: screenshots('bei', [
      ['1.webp', 'BatchEnhance Image source selection', 'Choose the selected image folder.'],
      ['2.webp', 'BatchEnhance Image upscale controls', 'Set scale and print-oriented options consistently.'],
      ['4.webp', 'BatchEnhance Image comparison view', 'Inspect the result rather than assuming enlargement fixed everything.'],
      ['5.webp', 'BatchEnhance Image batch output', 'Export the prepared image set locally.']
    ]),
    faq: [
      { q: 'Can enhancement repair every bad image?', a: 'No. It can improve size and presentation, but it cannot rescue weak composition, severe artifacts, or missing detail.' },
      { q: 'Is it only for AI images?', a: 'No. It can prepare ordinary photos and digital artwork as well.' },
      { q: 'Does it upload images?', a: 'No. Processing is local.' }
    ],
    relatedProducts: ['BGI', 'BRI', 'BTP'],
    relatedUseCases: ['enhance-images-for-printing', 'create-a-photobook-with-ai-for-gifting', 'create-posters-to-print-or-sell'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BRI',
    slug: 'batchresize-image',
    url: '/batchresize-image.html',
    name: 'BatchResize Image',
    seoTitle: 'BatchResize Image — Batch Image Resizer for Windows | 3thousand30',
    shortName: 'BatchResize Image',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['images', 'social', 'web'],
    status: 'released',
    featured: false,
    tagline: 'Turn one approved image set into the dimensions each channel needs.',
    description: 'A local Windows batch image resizer with platform presets, crop controls, live preview, and predictable folder output.',
    intro: 'BatchResize Image handles the repetitive versioning step after the creative work is approved. Choose a target size or preset, check the crop, and process the set locally instead of resizing each file by hand.',
    logo: '/Logos/BRI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9PPKDVXPTLV0',
    docsUrl: 'https://3thousand30.github.io/batchresizeimage-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price for your region.',
    privacyLabel: 'Fully local',
    privacyText: 'Source images, crop choices, resize settings, and outputs remain on the machine. No account, upload, or telemetry is required.',
    features: ['Resize a whole folder in one run', 'Use practical social, web, email, and marketplace presets', 'Control crop and aspect-ratio handling', 'Preview the result before processing', 'Keep source files separate from outputs', 'Work without a cloud upload'],
    audiences: ['Social teams preparing channel variants', 'Ecommerce sellers standardising listing images', 'Anyone maintaining web and email image sizes'],
    screenshotItems: screenshots('bri', [
      ['1.webp', 'BatchResize Image folder setup', 'Choose the approved source set.'],
      ['2.webp', 'BatchResize Image preset controls', 'Apply one repeatable target size.'],
      ['4.webp', 'BatchResize Image crop preview', 'Check what will be kept before processing.'],
      ['5.webp', 'BatchResize Image completed batch', 'Export a clean platform-ready folder.']
    ]),
    faq: [
      { q: 'Will every aspect ratio crop cleanly?', a: 'No. Review the preview, especially when faces, text, or products sit close to an edge.' },
      { q: 'Does it change the originals?', a: 'Use a separate output folder so the approved source set remains intact.' },
      { q: 'Does it need internet access?', a: 'No. Resizing is local.' }
    ],
    relatedProducts: ['BGI', 'BCI', 'BWI'],
    relatedUseCases: ['resize-images-for-different-social-platforms', 'mass-create-social-media-content', 'batch-create-images-for-social-media'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BWI',
    slug: 'batchwatermark-image',
    url: '/batchwatermark-image.html',
    name: 'BatchWatermark Image',
    seoTitle: 'BatchWatermark Image — Batch Image Watermarker for Windows | 3thousand30',
    shortName: 'BatchWatermark Image',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['images', 'social', 'rights'],
    status: 'released',
    featured: false,
    tagline: 'Apply text, a logo, or both across an image set after reviewing the placement.',
    description: 'A fully local Windows batch watermarker with text and logo layers, opacity, placement, tiling, preview, and controlled export.',
    intro: 'BatchWatermark Image is for proof sets, branded previews, and visible rights notices. Configure the mark once, inspect representative images, and export a separate sharing set without modifying the masters.',
    logo: '/Logos/BWI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9n3s7zrpxgph',
    docsUrl: 'https://3thousand30.github.io/batchwatermarkimage-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price for your region.',
    privacyLabel: 'Fully local',
    privacyText: 'Source images, watermark assets, preview states, and exported files stay on your machine with no cloud upload, account, or telemetry.',
    features: ['Add a text watermark, logo watermark, or both', 'Control position, opacity, scale, and tiling', 'Preview placement before the batch run', 'Create proof, branded, or rights-marked sets', 'Write results to a separate output folder', 'Process the full set locally'],
    audiences: ['Photographers sending client proofs', 'Creators sharing work before approval', 'Sellers adding a consistent visible brand or copyright line'],
    screenshotItems: screenshots('bwi', [
      ['1.webp', 'BatchWatermark Image source and watermark setup', 'Choose the source folder and visible mark.'],
      ['2.webp', 'BatchWatermark Image placement controls', 'Set position, opacity, and scale once.'],
      ['3.webp', 'BatchWatermark Image preview', 'Check legibility across representative images.'],
      ['4.webp', 'BatchWatermark Image batch result', 'Export the sharing copies locally.']
    ]),
    faq: [
      { q: 'Is a watermark a complete copyright-protection system?', a: 'No. It is a visible notice or sharing deterrent, not a guarantee against copying.' },
      { q: 'Can I keep clean masters?', a: 'Yes. Export watermarked copies to a separate folder and retain the original files.' },
      { q: 'Are images uploaded?', a: 'No. Watermarking is local.' }
    ],
    relatedProducts: ['BGI', 'BRI', 'BCI'],
    relatedUseCases: ['add-watermarks-before-sharing-images', 'add-copyright-information-to-images', 'mass-create-social-media-content'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BCI',
    slug: 'batchcompress-image',
    url: '/batchcompress-image.html',
    name: 'BatchCompress Image',
    seoTitle: 'BatchCompress Image — Batch Image Compressor for Windows | 3thousand30',
    shortName: 'BatchCompress Image',
    type: 'utility',
    typeLabel: 'Local utility',
    categories: ['images', 'web', 'storage'],
    status: 'released',
    featured: false,
    tagline: 'Reduce a folder’s image weight for web, email, storage, and delivery.',
    description: 'A fully local Windows batch image compressor with quality controls, before-and-after comparison, and clean output folders.',
    intro: 'BatchCompress Image makes size reduction a controlled batch step. Keep the original exports, test a representative quality setting, compare the result, then process the delivery or archive copies locally.',
    logo: '/Logos/BCI.webp',
    storeUrl: 'https://apps.microsoft.com/detail/9n1dbc2g87ht',
    docsUrl: 'https://3thousand30.github.io/batchcompressimage-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price for your region.',
    privacyLabel: 'Fully local',
    privacyText: 'Compression and comparison happen on the PC. Source images and output files are not uploaded to a cloud service.',
    features: ['Compress a complete image folder', 'Choose a quality target for the batch', 'Compare original and compressed output', 'Prepare lighter files for websites, email, and marketplaces', 'Keep source and compressed copies separate', 'Run without an account or upload'],
    audiences: ['Website owners improving page weight', 'Creators preparing email-friendly image sets', 'People reducing an archive or backup footprint'],
    screenshotItems: screenshots('bci', [
      ['1.webp', 'BatchCompress Image folder and quality setup', 'Choose a source set and initial quality target.'],
      ['2.webp', 'BatchCompress Image before and after comparison', 'Inspect visual quality before using the setting broadly.'],
      ['3.webp', 'BatchCompress Image completed results', 'Review the size reduction and exported folder.']
    ]),
    faq: [
      { q: 'Will compression always look identical?', a: 'No. Strong compression can introduce visible artifacts, so compare representative images before processing the whole set.' },
      { q: 'Should I replace the original files?', a: 'Keep the masters and create a separate delivery or archive copy unless you are certain the reduced files are sufficient.' },
      { q: 'Is it local?', a: 'Yes. No image upload is required.' }
    ],
    relatedProducts: ['BRI', 'BWI', 'BFO'],
    relatedUseCases: ['compress-images-to-save-storage-space', 'organise-and-prepare-a-working-file-collection'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BMP',
    slug: 'batch-merge-pdfs',
    url: '/batch-merge-pdfs.html',
    name: 'Batch Merge PDFs',
    seoTitle: 'Batch Merge PDFs — Offline PDF Merger for Windows | 3thousand30',
    shortName: 'Batch Merge PDFs',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'files', 'publishing'],
    status: 'released',
    featured: true,
    tagline: 'Combine a folder of PDFs into one ordered file without uploading the documents.',
    description: 'A lightweight local PDF merger for Windows with alphabetical ordering, folder-based output naming, optional page numbers, progress, and skip-existing support.',
    intro: 'Batch Merge PDFs turns a correctly named folder into one final PDF. It combines files in alphabetical filename order, can add fresh continuous page numbers, and keeps the full job on the PC.',
    logo: '/Logos/BMP.png',
    storeUrl: 'https://apps.microsoft.com/detail/9NVDT0TTN0WH',
    docsUrl: 'https://3thousand30.github.io/batchmergepdf-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price and promotion for your region.',
    privacyLabel: 'Fully local',
    privacyText: 'The source PDFs and merged result remain on your Windows machine. No account, subscription, or cloud upload by 3thousand30 is required.',
    features: ['Merge every PDF directly inside one folder', 'Use alphabetical filenames to control the order', 'Name the result after the source folder', 'Add continuous page numbers when useful', 'Skip an output that already exists', 'Track progress and open the output folder after completion'],
    audiences: ['People assembling chapters or exported sections', 'Teams combining reports, invoices, scans, or worksheets', 'Anyone avoiding online PDF-upload services'],
    screenshotItems: screenshots('bmp', [
      ['01-main-merge.png', 'Batch Merge PDFs folder and output setup', 'Choose the PDF folder, output location, and page-number option.'],
      ['02-merge-complete.png', 'Completed local merge in Batch Merge PDFs', 'Review the completed merge and open the output folder.'],
      ['03-getting-started.png', 'Batch Merge PDFs getting-started guidance', 'Use predictable filenames to control the final document order.']
    ]),
    faq: [
      { q: 'How is the merge order decided?', a: 'PDFs are merged in alphabetical filename order. Numbered prefixes such as 01, 02, and 03 make the intended order explicit.' },
      { q: 'Can it add page numbers?', a: 'Yes. You can add fresh continuous page numbers across the merged output.' },
      { q: 'Are PDFs uploaded?', a: 'No. The merge runs locally.' }
    ],
    relatedProducts: ['BSP', 'BTP', 'BT'],
    relatedUseCases: ['merge-pdfs-without-using-the-internet', 'create-a-poetry-book', 'translate-a-book-for-new-markets'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BSP',
    slug: 'batch-split-pdfs',
    url: '/batch-split-pdfs.html',
    name: 'Batch Split PDFs',
    seoTitle: 'Batch Split PDFs — Offline PDF Splitter for Windows | 3thousand30',
    shortName: 'Batch Split PDFs',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'files', 'productivity'],
    status: 'released',
    featured: false,
    tagline: 'Split one PDF or a whole folder into pages or fixed-size chunks locally.',
    description: 'A lightweight PDF splitter for Windows with single-file and folder modes, optional subfolder scanning, pages-per-file control, and predictable output names.',
    intro: 'Batch Split PDFs handles both the one-document job and the folder-wide job. Choose one page per output or a fixed number of pages per chunk, then follow the local batch without opening each PDF individually.',
    logo: '/Logos/BSP.png',
    storeUrl: 'https://apps.microsoft.com/detail/9MZKRHK6NRRS',
    docsUrl: 'https://3thousand30.github.io/batchsplitpdf-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price and promotion for your region.',
    privacyLabel: 'Fully local',
    privacyText: 'PDF reading, splitting, and file output happen locally on Windows. No account, subscription, or cloud upload by 3thousand30 is required.',
    features: ['Split one PDF into individual pages', 'Split one PDF into fixed-size chunks', 'Process all PDFs in a folder', 'Optionally include nested subfolders', 'Use automatic numbered output names', 'Track progress and safely skip existing outputs'],
    audiences: ['People extracting pages for review or upload', 'Teams breaking reports or scans into smaller packets', 'Publishers separating combined documents before a new workflow'],
    screenshotItems: screenshots('bsp', [
      ['01-single-pdf-split.png', 'Single-file setup in Batch Split PDFs', 'Split one PDF into individual pages or fixed-size chunks.'],
      ['02-folder-split-complete.png', 'Completed folder batch in Batch Split PDFs', 'Process a whole folder and review the completed outputs.']
    ]),
    faq: [
      { q: 'Can it create one file per page?', a: 'Yes. Set pages per file to 1.' },
      { q: 'Can it process subfolders?', a: 'Yes. Folder mode can optionally include PDFs inside nested folders.' },
      { q: 'Does splitting use the cloud?', a: 'No. The workflow is local.' }
    ],
    relatedProducts: ['BMP', 'BTP', 'BFO'],
    relatedUseCases: ['translate-a-book-for-new-markets', 'create-short-stories-for-teaching'],
    lastmod: '2026-08-07'
  },
  {
    code: 'BTP',
    slug: 'batch-text-to-pdf',
    url: '/batch-text-to-pdf.html',
    name: 'Batch Text to PDF',
    seoTitle: 'Batch Text to PDF — Batch PDF Creator for Windows | 3thousand30',
    shortName: 'Batch Text to PDF',
    type: 'utility',
    typeLabel: 'Local PDF utility',
    categories: ['pdf', 'publishing', 'files'],
    status: 'released',
    featured: true,
    tagline: 'Turn folders of Markdown, text, DOCX, and images into separate or combined PDFs.',
    description: 'A local Windows batch PDF maker with flexible page sizes, Markdown rendering, multilingual colour emoji, image pairing, combined output, and page numbering.',
    intro: 'Batch Text to PDF converts a mixed folder into finished PDFs in one run. Create one PDF per source or a single ordered document, pair same-named text and images, choose page dimensions, and keep the conversion local.',
    logo: '/Logos/BTP.png',
    storeUrl: 'https://apps.microsoft.com/detail/9NS1L0DK0FQL',
    docsUrl: 'https://3thousand30.github.io/batchtexttopdf-docs/',
    priceLabel: '$4.99 list price',
    priceNote: '25% launch discount through 6 August 2027. Microsoft Store applies regional pricing.',
    privacyLabel: 'Fully local',
    privacyText: 'Core conversion runs on your PC. No account, upload, AI service, analytics, or telemetry is required.',
    features: ['Convert Markdown, TXT, DOCX, JPG, PNG, WebP, and GIF sources', 'Create one PDF per source or one combined ordered PDF', 'Choose eight presets or custom page dimensions and margins', 'Add page numbers to individual or combined output', 'Auto-pair same-named text and image files', 'Preserve multilingual text and full-colour emoji'],
    audiences: ['Writers converting chapters or guides', 'Teachers creating worksheet and story packs', 'Publishers assembling illustrated drafts and small books'],
    screenshotItems: screenshots('btp', [
      ['01-mixed-source-batch.png', 'Mixed Markdown, text, DOCX, and image sources in Batch Text to PDF', 'Convert mixed file types in one local run.'],
      ['02-custom-page-size.png', 'Custom page dimensions and margins in Batch Text to PDF', 'Use book, document, square, or exact custom dimensions.'],
      ['03-auto-pair-images.png', 'Same-named text and image pairing in Batch Text to PDF', 'Pair illustrations before or after matching text.'],
      ['04-combined-document.png', 'Combined document setup in Batch Text to PDF', 'Turn an ordered folder into one page-numbered document.'],
      ['05-completed-conversion.png', 'Completed Batch Text to PDF conversion', 'Review converted, skipped, renamed, and failed sources.'],
      ['06-local-processing.png', 'Local-processing information in Batch Text to PDF', 'Keep document conversion on the PC.']
    ]),
    faq: [
      { q: 'Which source formats are supported?', a: 'Markdown, plain text, DOCX, JPG, JPEG, PNG, WebP, and GIF. Existing PDFs are skipped rather than reconverted.' },
      { q: 'Does DOCX preserve the original Word layout?', a: 'No. It extracts paragraph text; original styling, embedded images, and page layout are not reproduced.' },
      { q: 'Can it combine a whole folder?', a: 'Yes. Combined mode processes supported files in filename order and can add page numbers.' },
      { q: 'Does it need an AI service?', a: 'No. PDF conversion is local and does not require an AI provider.' }
    ],
    relatedProducts: ['BMP', 'BSP', 'BGT'],
    relatedUseCases: ['batch-create-pdfs-from-text', 'create-a-colouring-book-for-children', 'create-a-poetry-book', 'create-short-stories-for-teaching'],
    lastmod: '2026-08-07'
  },
  {
    code: 'KR',
    slug: 'key-rush',
    url: '/key-rush.html',
    name: 'Key Rush',
    seoTitle: 'Key Rush — Offline Typing Game for Windows | 3thousand30',
    shortName: 'Key Rush',
    type: 'game',
    typeLabel: 'Offline game',
    categories: ['game', 'typing', 'offline'],
    status: 'released',
    featured: true,
    tagline: 'A Windows typing game staged like a live breach console.',
    description: 'Offline-first typing action with story missions, an accelerating endless lane, no-fail zen practice, local top-10 boards, and no account or telemetry.',
    intro: 'Key Rush makes typing practice feel like a system under pressure. Clear three hacker-thriller story missions, chase a score as Endless accelerates, or stay in rhythm in Zen without a fail state.',
    logo: '/Logos/KR.png',
    storeUrl: 'https://apps.microsoft.com/detail/9MW7722B1026',
    docsUrl: 'https://3thousand30.github.io/keyrush-docs/',
    priceLabel: 'Buy once',
    priceNote: 'Microsoft Store shows the current price and promotion for your region.',
    privacyLabel: 'Offline-first · local scores',
    privacyText: 'Play, settings, local top-10 boards, score tags, and saved result cards stay on the machine. No account or telemetry is required.',
    features: ['Play Story, Endless, or Zen modes', 'Clear nine levels across three story chapters', 'Survive an endless lane that speeds up over time', 'Practise in a no-fail Zen passage mode', 'Keep local top-10 boards for every mode', 'Adjust motion, font size, contrast, sound, and music'],
    audiences: ['Players who want a stylish typing game', 'People practising accuracy without an account', 'Score chasers sharing one local Windows PC'],
    screenshotItems: screenshots('kr', [
      ['02-home-menu.png', 'Key Rush terminal-style main menu', 'Choose Story, Endless, or Zen.'],
      ['03-chapter-select.png', 'Key Rush story chapter selection', 'Run three hacker-thriller story missions.'],
      ['08-story-gameplay.png', 'Typing action during a Key Rush story mission', 'Type through the live breach console.'],
      ['11-endless-life-bonus.png', 'Key Rush endless mode under pressure', 'Chase the local board as the lane accelerates.'],
      ['09-zen-gameplay.png', 'Key Rush no-fail Zen typing mode', 'Practise rhythm and accuracy without a fail state.'],
      ['04-leaderboard.png', 'Key Rush local top-ten leaderboard', 'Keep score chasing local to the machine.']
    ]),
    faq: [
      { q: 'Can I play offline?', a: 'Yes. The core game is offline-first.' },
      { q: 'Does it require an account?', a: 'No. Scores and settings are stored locally.' },
      { q: 'Is Zen mode timed?', a: 'Zen is designed as a no-fail practice lane so you can focus on rhythm and accuracy rather than losing a run.' }
    ],
    relatedProducts: ['BGT', 'BFO'],
    relatedUseCases: [],
    lastmod: '2026-08-07'
  }
];
