function useCase(data) {
  return Object.assign({
    status: 'published',
    lastmod: '2026-08-07',
    proofLinks: [],
    relatedUseCases: [],
    faq: []
  }, data, { url: `/use-cases/${data.slug}.html` });
}

module.exports = [
  useCase({
    id: 1,
    slug: 'create-a-photobook-with-ai-for-gifting',
    title: 'Create a Photobook With AI for Gifting',
    shortTitle: 'AI photobook for gifting',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Turn a themed AI image collection into a reviewed, print-ready physical book instead of a folder of disconnected generations.',
    scenario: 'You want to create a personal coffee-table book for a friend or family member. The gift needs a clear theme, enough visual range to stay interesting, and print files that survive physical production.',
    outcome: 'A deliberately sequenced, print-ready photobook that can be gifted privately or published through a print-on-demand service.',
    products: ['BGI', 'BEI', 'BTP', 'BMP'],
    inputs: ['A theme broad enough to support a complete book', 'A scene or topic list', 'A target trim size and rough page count', 'Time for visual selection and print review'],
    steps: [
      { title: 'Define the book, not one prompt', body: 'Choose a theme, audience, trim size, and approximate number of spreads. Build scene ideas, recurring motifs, section breaks, and cover directions before generating anything.' },
      { title: 'Generate a wider image set', body: 'In Batch Generate Image with any AI, set a reusable visual direction and an appropriate page ratio. Generate more candidates than the book needs so selection, not luck, controls the result.' },
      { title: 'Reject and sequence', body: 'Remove off-theme images, obvious artifacts, weak compositions, and repetitive scenes. Arrange the survivors so colour, subject, and mood change with intention.' },
      { title: 'Prepare the selected images for print', body: 'Use Batch Enhance Image only on the final shortlist. Check target pixel dimensions and inspect enlarged files closely; upscaling cannot repair a fundamentally poor source.' },
      { title: 'Create and assemble the pages', body: 'Use Batch Text to PDF for text, image, or paired text-image pages. If sections were exported separately, use numbered filenames and Batch Merge PDFs to assemble the final order locally.' },
      { title: 'Proof a physical copy', body: 'Check margins, crop, colour, page order, and spine/cover requirements against the printer’s current specification. A digital PDF review does not replace a physical proof.' }
    ],
    review: ['Does the sequence feel like one object rather than a prompt dump?', 'Are weak hands, text artifacts, and near-duplicates removed?', 'Do the final pixel dimensions fit the printer’s specification?', 'Has a physical proof been checked before gifting or selling?'],
    limitation: 'AI generation does not guarantee character consistency, printable detail, or correct typography. Human selection, layout work, and printer-specific proofing remain essential.',
    privacy: 'Image prompts go to the AI provider selected in Batch Generate Image with any AI. Enhancement, PDF conversion, merging, and the saved outputs run locally.',
    proofLinks: [
      { label: 'People, Places & Perspective on Amazon', url: 'https://www.amazon.com/dp/B0GWVL1D6R' },
      { label: 'People, Places & Perspective on Lulu', url: 'https://www.lulu.com/shop/proyogi-baba/people-places-perspective/paperback/product-yvr56g6.html?page=1&pageSize=4' }
    ],
    relatedUseCases: ['create-a-colouring-book-for-children', 'create-an-inspirational-family-book', 'enhance-images-for-printing'],
    faq: [
      { q: 'Do I need to be a designer?', a: 'You do not need a design title, but you do need judgment. Selection, sequencing, margins, and proofing determine whether the result feels deliberate.' },
      { q: 'Can I sell the finished book?', a: 'Potentially, if you have the necessary rights and the work meets the chosen platform’s current content and print requirements. Check those requirements before publication.' }
    ]
  }),
  useCase({
    id: 2,
    slug: 'mass-create-social-media-content',
    title: 'Plan and Create Social Media Content in Batches',
    shortTitle: 'Batch social content',
    category: 'social',
    categoryLabel: 'Social & image production',
    summary: 'Build a reviewed campaign pack containing text, images, platform sizes, and optional marked preview copies.',
    scenario: 'A creator or small seller needs a month of useful posts around one launch or topic, but producing each post from scratch causes voice drift and last-minute publishing.',
    outcome: 'A calm, organised folder of reviewed post copy and matching image variants ready for scheduling or manual publication.',
    products: ['BGT', 'BGI', 'BRI', 'BWI'],
    inputs: ['A campaign goal and audience', 'Three to five content pillars', 'A topic list and call-to-action rules', 'Brand voice and visual references', 'Target platform dimensions'],
    steps: [
      { title: 'Plan the campaign before generating', body: 'Define the purpose, audience, content pillars, selling frequency, and calls to action. A useful batch begins with a deliberate topic list, not ninety versions of the same generic idea.' },
      { title: 'Generate the text batch', body: 'In Batch Generate Text with any AI, use a reusable persona and the required post formats. Preview a small sample first, then generate the broader batch only when the voice and structure are working.' },
      { title: 'Generate a matching visual set', body: 'In Batch Generate Image with any AI, set a visual persona, reference direction, and ratios suited to the campaign. Keep enough variation for selection without letting the set lose its identity.' },
      { title: 'Run a human critic pass', body: 'Remove repetition, hollow claims, awkward calls to action, unsafe advice, and images with obvious defects. Verify factual or product-specific claims against a trusted source.' },
      { title: 'Prepare channel variants', body: 'Use Batch Resize Image to produce the dimensions each platform actually needs. Check crops on text-heavy images and keep platform folders separate.' },
      { title: 'Create proofs when useful', body: 'Use Batch Watermark Image for client previews, draft packs, or branded sample sets. Keep clean masters and publish only the approved version.' }
    ],
    review: ['Does every post say something distinct?', 'Are factual claims and links verified?', 'Do crops preserve faces, products, and on-image text?', 'Is the final pack named clearly enough to schedule without guessing?'],
    limitation: 'Batch creation is not batch autopublishing. Human review is necessary for accuracy, taste, platform fit, and brand safety.',
    privacy: 'Text and image generation requests go to the providers you choose. Resizing, watermarking, file storage, and review remain local.',
    proofLinks: [{ label: 'Proyogi Baba on X', url: 'https://x.com/ProyogiBaba' }],
    relatedUseCases: ['batch-create-images-for-social-media', 'resize-images-for-different-social-platforms', 'add-watermarks-before-sharing-images'],
    faq: [
      { q: 'Should I publish everything the batch creates?', a: 'No. Generate for range, then reject aggressively. Volume is useful only when review prevents it from becoming repetitive noise.' },
      { q: 'Is this only for creators?', a: 'No. The same structure works for ecommerce launches, product education, events, and small-business campaigns.' }
    ]
  }),
  useCase({
    id: 3,
    slug: 'create-a-custom-invitation',
    title: 'Create a Custom Invitation for Any Occasion',
    shortTitle: 'Custom invitation set',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Draft personalised invitation wording, create a matching visual, and export a shareable or printable PDF.',
    scenario: 'You are preparing invitations for a birthday, anniversary, family gathering, workshop, or small wedding and want several wording options without losing the essential details.',
    outcome: 'An approved invitation in a consistent visual style, plus clearly named variants when different guests need different wording.',
    products: ['BGT', 'BGI', 'BTP'],
    inputs: ['Event name, date, time, location, and contact details', 'Audience and desired tone', 'Any dress, RSVP, accessibility, or gift guidance', 'Print or digital delivery size'],
    steps: [
      { title: 'Lock the facts first', body: 'Create one source note containing the confirmed event details. Treat that note as authoritative so generated variants do not invent locations, dates, or RSVP instructions.' },
      { title: 'Generate wording options', body: 'Use Batch Generate Text with any AI to create a small set of tones—formal, warm, playful, concise—while explicitly preserving the source facts. Select one before personalising names or guest groups.' },
      { title: 'Create the visual direction', body: 'Use Batch Generate Image with any AI for background or illustration options at the intended aspect ratio. Avoid asking the image model to render the final invitation text; add verified text during layout instead.' },
      { title: 'Review every visible detail', body: 'Check names, spelling, time zone, address, RSVP deadline, phone number, and links. Ask another person to read the final copy because familiarity hides mistakes.' },
      { title: 'Export the finished invitation', body: 'Prepare the final text and image inputs, then use Batch Text to PDF for a consistent printable or shareable document. Test the PDF on a phone and, if printing, on paper.' }
    ],
    review: ['Are date, time, address, and RSVP details exact?', 'Does the tone fit the people receiving it?', 'Is text readable against the image?', 'Does the printed size match the planned envelope or paper?'],
    limitation: 'AI is useful for wording and visual exploration, but event facts must come from a confirmed human source. Generated text inside images is unreliable.',
    privacy: 'Generation requests go to the AI providers you select. Final PDF conversion and stored files remain local.',
    relatedUseCases: ['create-an-inspirational-family-book', 'create-posters-to-print-or-sell'],
    faq: [{ q: 'Can I create personalised variants?', a: 'Yes. Keep a master facts file and generate or edit variants from it, then verify every personalised name and instruction before sending.' }]
  }),
  useCase({
    id: 4,
    slug: 'create-a-colouring-book-for-children',
    title: 'Create a Colouring Book for Children',
    shortTitle: 'Children’s colouring book',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Develop a safe, coherent line-art theme and turn the selected pages into a printable book.',
    scenario: 'A parent, teacher, or independent publisher wants a small colouring book around dinosaurs, local animals, vehicles, or a child-friendly story theme.',
    outcome: 'A reviewed set of simple black-and-white pages assembled at one print size with a cover and a physical proof.',
    products: ['BGI', 'BEI', 'BTP'],
    inputs: ['Age range and theme', 'A page list with one clear subject per page', 'Target trim size and printer specification', 'Safety and appropriateness rules'],
    steps: [
      { title: 'Define age and page complexity', body: 'Younger children need larger shapes and less detail; older children can handle denser scenes. Write the rule into the visual persona so the set does not swing between toddler pages and adult line art.' },
      { title: 'Generate line-art candidates', body: 'In Batch Generate Image with any AI, set a consistent black-line direction, plain background, and the target aspect ratio. Generate alternatives because stray grey shading, broken outlines, and malformed objects are common rejection reasons.' },
      { title: 'Review for safety and usability', body: 'Reject frightening details, unsafe actions, accidental words, trademarks, and confusing anatomy. Print a few test pages to see whether the line weight is actually colourable.' },
      { title: 'Prepare the selected artwork', body: 'Use Batch Enhance Image only if the selected pages need larger pixel dimensions. Inspect the outlines after scaling and keep the original files.' },
      { title: 'Assemble the printable book', body: 'Use Batch Text to PDF to place image pages at a consistent trim size and create a combined document. Add a separate title or instruction page if needed, then review every page boundary.' },
      { title: 'Order a physical proof', body: 'Check show-through, line weight, safe margins, binding loss, and whether the page backs should remain blank. Update the source set before publishing more copies.' }
    ],
    review: ['Is every page suitable for the stated age?', 'Are outlines clear at print size?', 'Are accidental text and logos absent?', 'Has someone coloured a physical test page?'],
    limitation: 'Image models often produce inconsistent objects, incomplete outlines, and unwanted shading. A child-safety and print-usability review cannot be automated away.',
    privacy: 'Image prompts go to your selected provider. Enhancement, PDF creation, and the saved page files stay local.',
    relatedUseCases: ['create-short-stories-for-teaching', 'enhance-images-for-printing', 'create-a-photobook-with-ai-for-gifting'],
    faq: [{ q: 'Can I publish the book commercially?', a: 'Potentially, but you must check the rights attached to your chosen model and assets, avoid protected characters or brands, and meet the printer or marketplace rules.' }]
  }),
  useCase({
    id: 5,
    slug: 'create-an-inspirational-family-book',
    title: 'Create an Inspirational Book for Your Family',
    shortTitle: 'Inspirational family book',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Turn family lessons, memories, sayings, and images into a private book with a clear human voice.',
    scenario: 'You want to preserve the advice, stories, and encouragement that matter in your family instead of leaving them scattered across messages and notebooks.',
    outcome: 'A personal, reviewed PDF or printed book organised around family themes, with source memories kept separate from AI-assisted drafting.',
    products: ['BGT', 'BGI', 'BTP', 'BMP'],
    inputs: ['Recorded memories, quotes, lessons, and names', 'Permission for private stories or photographs', 'A chapter outline', 'A preferred tone and audience'],
    steps: [
      { title: 'Collect the human source material', body: 'Write or transcribe the real memories first. Label who supplied each story and flag private details that should not appear in a shared edition.' },
      { title: 'Build a chapter map', body: 'Group the material into themes such as resilience, humour, work, relationships, or family rituals. Use Batch Generate Text with any AI to help structure or rewrite, but do not let it invent family history.' },
      { title: 'Review the voice with the family', body: 'Check names, events, and sensitive language with the people involved. Preserve disagreement or uncertainty rather than smoothing it into false certainty.' },
      { title: 'Create supporting images if wanted', body: 'Use Batch Generate Image with any AI for symbolic or decorative illustrations, not fake documentary evidence. Label generated visuals appropriately if readers might otherwise mistake them for real family photographs.' },
      { title: 'Create the document', body: 'Use Batch Text to PDF to convert the approved chapters and paired images. If chapters were produced separately, number them clearly and use Batch Merge PDFs for the final assembly.' },
      { title: 'Choose the sharing boundary', body: 'Decide whether the result is for one household, the extended family, or public sale. Remove material that does not have permission for the chosen boundary.' }
    ],
    review: ['Are factual memories distinguished from generated connective writing?', 'Did the people named in sensitive stories approve?', 'Are generated images clearly decorative rather than documentary?', 'Is there a private master copy separate from public variants?'],
    limitation: 'AI cannot verify family history or grant consent. It should support organisation and drafting, not replace the people whose memories make the book valuable.',
    privacy: 'Only send source material to an AI provider if everyone involved accepts that choice. PDF conversion and file assembly remain local.',
    relatedUseCases: ['create-a-photobook-with-ai-for-gifting', 'create-short-stories-for-teaching', 'batch-create-pdfs-from-text'],
    faq: [{ q: 'Should I upload private family stories to an AI provider?', a: 'Only after understanding that provider’s current data practices and receiving appropriate permission. Sensitive material can also be edited manually without sending it to an external model.' }]
  }),
  useCase({
    id: 6,
    slug: 'create-short-stories-for-teaching',
    title: 'Create Short Stories for Teaching',
    shortTitle: 'Teaching story set',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Create a themed set of age-appropriate stories and illustrations, then turn them into classroom or home-learning PDFs.',
    scenario: 'A parent or teacher needs several short stories that reinforce a vocabulary list, social lesson, historical topic, or reading level.',
    outcome: 'A reviewed pack of short stories, optional illustrations, and printable PDFs matched to a clearly stated learner level.',
    products: ['BGT', 'BGI', 'BTP', 'BMP', 'BSP'],
    inputs: ['Learner age and reading level', 'Learning objective and required vocabulary', 'Length and content boundaries', 'Review criteria for accuracy and safety'],
    steps: [
      { title: 'Define the learning objective', body: 'Write what the learner should understand or practise after reading. Include vocabulary, reading length, cultural context, and topics that must be avoided.' },
      { title: 'Generate a small pilot set', body: 'Use Batch Generate Text with any AI to draft two or three stories first. Check reading level, repetition, facts, and whether the lesson is actually present before expanding the batch.' },
      { title: 'Review as an educator', body: 'Correct inaccuracies, stereotypes, unsafe advice, and language that is too difficult or too simplistic. AI-generated educational content needs subject-matter review.' },
      { title: 'Create optional illustrations', body: 'Use Batch Generate Image with any AI and a stable child-appropriate direction. Check every visual for relevance, safety, accidental text, and character inconsistency.' },
      { title: 'Produce the PDF set', body: 'Use Batch Text to PDF for separate story PDFs or one combined class pack. Use Batch Merge PDFs when separately exported sections need assembly, and Batch Split PDFs when a combined pack must later become individual handouts.' },
      { title: 'Test with one learner', body: 'Observe where the reader hesitates or misunderstands. Revise the source text, then regenerate or rebuild only the affected material.' }
    ],
    review: ['Does the story meet the stated learning objective?', 'Are facts checked by a qualified person?', 'Is the reading level genuinely appropriate?', 'Are illustrations safe and relevant?'],
    limitation: 'Generated stories can contain subtle factual errors, stereotypes, or age-inappropriate material. A teacher or informed adult must review before use.',
    privacy: 'Avoid including identifiable learner data in prompts. Generation goes to the selected providers; PDF assembly stays local.',
    relatedUseCases: ['create-a-colouring-book-for-children', 'batch-create-pdfs-from-text', 'merge-pdfs-without-using-the-internet'],
    faq: [{ q: 'Can this replace curriculum material?', a: 'No. Treat it as draft or supplementary material that needs review against the curriculum and the learner’s actual needs.' }]
  }),
  useCase({
    id: 7,
    slug: 'create-a-poetry-book',
    title: 'Create a Poetry Book to Publish or Sell',
    shortTitle: 'Poetry book workflow',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Develop, curate, revise, and assemble a coherent poetry collection rather than publishing a raw generation dump.',
    scenario: 'A writer wants to explore a theme through many poem drafts, select the strongest work, and prepare a small print or digital collection.',
    outcome: 'A human-curated poetry manuscript with a deliberate sequence, optional artwork, and a print-ready PDF proof.',
    products: ['BGT', 'BGI', 'BTP', 'BMP'],
    inputs: ['A theme, emotional range, and intended reader', 'Original notes, phrases, or experiences', 'Form and length constraints', 'A publication and rights plan'],
    steps: [
      { title: 'Define the collection’s boundaries', body: 'Choose the theme, forms, length range, and voice rules. If the work uses AI assistance, decide how that will be described before publication.' },
      { title: 'Generate drafts, not finished truth', body: 'Use Batch Generate Text with any AI to explore prompts, images, forms, and variations. Avoid requesting imitation of a living poet and keep your own source notes central.' },
      { title: 'Curate and rewrite heavily', body: 'Reject generic metaphors, repeated structures, and lines that merely sound poetic. Rewrite selected pieces until the language earns its place in the collection.' },
      { title: 'Build the sequence', body: 'Arrange the poems by movement, contrast, and emotional rhythm. Read the entire manuscript aloud and remove pieces that weaken the whole.' },
      { title: 'Add artwork only when it contributes', body: 'Use Batch Generate Image with any AI for a cover or restrained section art if it improves the object. Do not force an illustration onto every poem.' },
      { title: 'Create and proof the book', body: 'Use Batch Text to PDF for consistent pages and Batch Merge PDFs if cover, front matter, and body are separate exports. Review line breaks and page turns on a physical proof.' }
    ],
    review: ['Does each poem contribute something distinct?', 'Are clichés and model-like repetition removed?', 'Are line breaks correct in the PDF?', 'Are rights and AI-assistance disclosures appropriate for the chosen platform?'],
    limitation: 'Generation can create fluent but generic verse and can echo familiar language. Original judgment, rewriting, rights review, and honest disclosure are the author’s responsibility.',
    privacy: 'Text and image requests go to the providers selected in the generative apps. PDF conversion and merging remain local.',
    relatedUseCases: ['create-song-lyrics-for-inspiration', 'batch-create-pdfs-from-text', 'create-posters-to-print-or-sell'],
    faq: [{ q: 'Can I publish AI-assisted poetry?', a: 'Rules differ by platform and jurisdiction. Check the current requirements, retain your process notes, avoid protected imitation, and describe the work honestly.' }]
  }),
  useCase({
    id: 8,
    slug: 'create-song-lyrics-for-inspiration',
    title: 'Create Song Lyrics for Inspiration',
    shortTitle: 'Lyric idea batches',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Generate original hooks, themes, images, and structural alternatives as raw material for human songwriting.',
    scenario: 'A songwriter has a theme or emotional direction but wants many possible hooks, rhyme families, perspectives, and verse structures to react against.',
    outcome: 'An organised local notebook of selected lyric fragments and drafts that the songwriter can rewrite into an original song.',
    products: ['BGT'],
    inputs: ['Theme, narrator, and emotional movement', 'Desired structure or section labels', 'Original phrases or story notes', 'Clear rules against artist imitation'],
    steps: [
      { title: 'Start from your own idea', body: 'Write the story, emotion, key images, and point of view before generating. The model should expand a creative brief, not replace the reason the song exists.' },
      { title: 'Generate different kinds of material', body: 'Use Batch Generate Text with any AI for hook alternatives, rhyme families, verse angles, bridge ideas, and structural variations. Ask for contrast rather than thirty near-identical full songs.' },
      { title: 'Avoid imitation prompts', body: 'Describe musical or emotional qualities in general terms instead of requesting the voice of a living artist. Do not reuse existing lyrics or near-verbatim phrases.' },
      { title: 'Select fragments, then rewrite', body: 'Pull the few lines or images that unlock something useful. Rewrite for singability, breath, stress, melody, and personal meaning.' },
      { title: 'Check originality before release', body: 'Search distinctive phrases, review any collaborators’ contributions, and keep a record of your human edits and source notes.' }
    ],
    review: ['Does the lyric sound specific to your song rather than generically “poetic”?', 'Can each line be sung naturally?', 'Were living-artist imitation and existing lyrics avoided?', 'Were distinctive phrases checked before release?'],
    limitation: 'Generated wording can resemble common or existing phrases. It does not provide a guarantee of originality, ownership, or clearance.',
    privacy: 'The selected text provider receives the prompt. Drafts and output files are saved locally by Batch Generate Text with any AI.',
    relatedUseCases: ['create-a-poetry-book', 'create-short-stories-for-teaching'],
    faq: [{ q: 'Can I ask for lyrics “in the style of” a famous living artist?', a: 'Use general musical qualities and your own references instead. The goal is original material, not imitation of a living creator.' }]
  }),
  useCase({
    id: 9,
    slug: 'batch-create-images-for-social-media',
    title: 'Batch-Create Images for Social Media',
    shortTitle: 'Batch social images',
    category: 'social',
    categoryLabel: 'Social & image production',
    summary: 'Generate a coherent visual series for a campaign, challenge, launch, or month-long content plan.',
    scenario: 'You already have the campaign topics and copy but need a visual set that feels related without repeating one composition thirty times.',
    outcome: 'A selected master folder of campaign images plus platform-ready variants, organised by topic and channel.',
    products: ['BGI', 'BRI'],
    inputs: ['Campaign topic list', 'Visual persona or reference direction', 'Brand exclusions and required colours', 'Target platforms and dimensions'],
    steps: [
      { title: 'Map one visual job to each topic', body: 'Decide whether each post needs a concept image, product scene, quote background, announcement graphic, or something else. Do not generate decoration without a publishing purpose.' },
      { title: 'Set the reusable visual system', body: 'Configure style, aspect ratio, visual persona, and any reference images in Batch Generate Image with any AI. Test a few representative topics before running the complete list.' },
      { title: 'Generate alternatives', body: 'Create enough range to reject malformed objects, weak composition, accidental text, and images that are too similar to one another.' },
      { title: 'Select a coherent master set', body: 'Review the campaign as a grid. Keep visual rhythm and brand fit in mind, not only whether each image works alone.' },
      { title: 'Resize after selection', body: 'Use Batch Resize Image to produce platform-specific copies from approved masters. Review crops where faces, products, or text-adjacent space matter.' },
      { title: 'Name for publication', body: 'Use clear filenames or folders that connect every image to its topic and platform so scheduling does not become another manual puzzle.' }
    ],
    review: ['Does each image support a specific post?', 'Is the set coherent without being repetitive?', 'Are accidental text and obvious generation defects removed?', 'Are platform crops manually checked?'],
    limitation: 'Visual personas and references improve consistency but do not guarantee identical characters, products, or typography across a batch.',
    privacy: 'Generation requests go to the provider selected in Batch Generate Image with any AI. Resizing and stored files remain local.',
    relatedUseCases: ['mass-create-social-media-content', 'resize-images-for-different-social-platforms', 'add-copyright-information-to-images'],
    faq: [{ q: 'Should I generate directly at every platform size?', a: 'Usually it is cleaner to select one strong master set first, then create channel variants with a controlled resize and crop pass.' }]
  }),
  useCase({
    id: 10,
    slug: 'create-posters-to-print-or-sell',
    title: 'Create Posters to Print or Sell',
    shortTitle: 'Poster collection workflow',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Generate a themed poster collection, prepare selected artwork for target sizes, and create marked previews without damaging the masters.',
    scenario: 'An artist or small seller wants a focused poster series for home printing, a market stall, or an online storefront.',
    outcome: 'A small, coherent collection of high-resolution poster masters, print proofs, and separate web-preview files.',
    products: ['BGI', 'BEI', 'BRI', 'BWI'],
    inputs: ['Theme and audience', 'Target print sizes and aspect ratios', 'A rights-safe visual direction', 'Printer and storefront specifications'],
    steps: [
      { title: 'Design the collection before the posters', body: 'Choose the number of pieces, shared visual rules, intended room or customer, and target aspect ratios. A series needs variation and a recognizable identity.' },
      { title: 'Generate at the right shape', body: 'In Batch Generate Image with any AI, choose the closest available ratio and a reusable visual direction. Do not rely on generated lettering for final poster typography.' },
      { title: 'Select for a physical object', body: 'Reject images that only look good as thumbnails. Inspect edges, fine detail, faces, and negative space at full size.' },
      { title: 'Prepare print masters', body: 'Use Batch Enhance Image on the selected files and check the required pixel dimensions for each final size. Keep a separate master for every aspect ratio rather than stretching one file.' },
      { title: 'Create storefront previews', body: 'Use Batch Resize Image for lighter web copies and Batch Watermark Image for visible preview marks when useful. Keep the clean print files offline and separate.' },
      { title: 'Proof and list honestly', body: 'Order or make a test print, verify crop and colour, and ensure the listing describes the actual size, medium, and fulfilment method.' }
    ],
    review: ['Does the set feel like a collection?', 'Are print dimensions sufficient?', 'Has generated text been replaced with verified typography?', 'Are web previews separate from clean masters?'],
    limitation: 'Upscaling cannot guarantee sharp large-format prints, and screen colour does not guarantee printer colour. A physical proof remains necessary.',
    privacy: 'Generation goes to the image provider you choose. Enhancement, resizing, watermarking, and saved files stay local.',
    relatedUseCases: ['enhance-images-for-printing', 'add-watermarks-before-sharing-images', 'compress-images-to-save-storage-space'],
    faq: [{ q: 'Can one square image become every poster size?', a: 'Not cleanly. Different aspect ratios need deliberate crops or separately composed masters.' }]
  }),
  useCase({
    id: 11,
    slug: 'publish-content-in-different-languages',
    title: 'Publish Content in Different Languages',
    shortTitle: 'Multilingual content set',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Translate a finished document set into multiple languages while keeping review, naming, and edition control visible.',
    scenario: 'A creator or small team has approved guides, help pages, product notes, or campaign documents and wants language-specific versions for different audiences.',
    outcome: 'Separate, reviewed language folders with a traceable relationship to the approved source set.',
    products: ['BT'],
    inputs: ['A frozen source-language folder', 'Target languages and locales', 'A glossary of names and fixed terms', 'A native or qualified reviewer for each public language'],
    steps: [
      { title: 'Freeze the source edition', body: 'Correct and approve the source documents first. Assign a version or date so every translation can be traced back to the same text.' },
      { title: 'Create the terminology rules', body: 'List product names, people, places, phrases that should not be translated, and preferred terminology. Locale matters: the same language can differ by market.' },
      { title: 'Run a small translation sample', body: 'Use Batch Translate Text with any AI on representative files before processing the full set. Evaluate tone, formatting, names, headings, and repeated terminology.' },
      { title: 'Translate into separated folders', body: 'Run the approved configuration for each target language and keep output directories clearly labelled by language and source version.' },
      { title: 'Use human language review', body: 'Have a capable reviewer correct meaning, tone, cultural fit, and layout. Back-translation can surface problems but does not replace a native review.' },
      { title: 'Publish as distinct editions', body: 'Keep canonical source links and language labels clear. When the source changes, update translations deliberately rather than silently drifting out of sync.' }
    ],
    review: ['Is every translation tied to one approved source version?', 'Are names and product terms consistent?', 'Did a qualified person review public-facing output?', 'Are language and locale labels correct?'],
    limitation: 'AI translation can miss context, idiom, legal meaning, and culturally sensitive nuance. High-stakes material requires qualified professional review.',
    privacy: 'Documents are sent to the AI provider selected in Batch Translate Text with any AI. The translated files are saved locally and are not stored by a separate 3thousand30 service.',
    relatedUseCases: ['translate-a-book-for-new-markets', 'batch-create-pdfs-from-text'],
    faq: [{ q: 'Can I publish without a human reviewer?', a: 'For public work, that is risky. At minimum, have a fluent reviewer check meaning, terminology, tone, and formatting.' }]
  }),
  useCase({
    id: 12,
    slug: 'translate-a-book-for-new-markets',
    title: 'Translate a Book for New Markets',
    shortTitle: 'Book translation workflow',
    category: 'books',
    categoryLabel: 'Books & publishing',
    summary: 'Translate a complete manuscript, review it as a new edition, and rebuild a language-specific print or digital book.',
    scenario: 'An independent author has a finished book and wants to test a German, Spanish, or other language edition without losing chapter order or key terminology.',
    outcome: 'A reviewed translation manuscript and a separate language edition prepared against the current publishing specification.',
    products: ['BT', 'BTP', 'BMP', 'BSP'],
    inputs: ['A final source manuscript', 'Rights to create the translation', 'Target language and market', 'Character/name glossary', 'A fluent editor or translator'],
    steps: [
      { title: 'Prepare the source manuscript', body: 'Remove unresolved edits and split the source into predictable chapter files if that makes review easier. Keep the original edition unchanged.' },
      { title: 'Build a book-specific glossary', body: 'Record character names, invented terms, recurring phrases, tone, dialogue rules, and words that must remain unchanged.' },
      { title: 'Translate a representative chapter', body: 'Use Batch Translate Text with any AI on one chapter containing dialogue, description, headings, and difficult terms. Revise the instructions before translating the complete manuscript.' },
      { title: 'Edit as a book, not a file conversion', body: 'A fluent reviewer must check voice, continuity, cultural context, and repeated terminology across chapters. Track corrections so later chapters receive the same treatment.' },
      { title: 'Rebuild the language edition', body: 'Use Batch Text to PDF for corrected chapter inputs. Use Batch Merge PDFs to assemble numbered sections, or Batch Split PDFs when a combined proof needs to return to chapter-sized review files.' },
      { title: 'Proof the new layout', body: 'Translated text changes line length and page count. Check contents, page breaks, headers, cover/spine dimensions, and platform metadata as a new edition.' }
    ],
    review: ['Are translation rights clear?', 'Is terminology consistent across the whole book?', 'Did a fluent editor review voice and cultural context?', 'Was the final layout proofed as a separate edition?'],
    limitation: 'A machine-translated manuscript is not a publication-ready book. Rights, literary editing, cultural review, and edition-specific layout remain human responsibilities.',
    privacy: 'Book text goes to the provider selected in Batch Translate Text with any AI. PDF conversion, splitting, merging, and final stored files remain local.',
    relatedUseCases: ['publish-content-in-different-languages', 'create-a-poetry-book', 'merge-pdfs-without-using-the-internet'],
    faq: [{ q: 'Why not translate the final PDF and publish it directly?', a: 'Book translation changes text length, line breaks, page count, and sometimes structure. Rebuilding and proofing the target-language edition gives you control over those changes.' }]
  }),
  useCase({
    id: 13,
    slug: 'add-watermarks-before-sharing-images',
    title: 'Add Watermarks Before Sharing Images',
    shortTitle: 'Watermarked proof set',
    category: 'social',
    categoryLabel: 'Social & image production',
    summary: 'Create a separate proof or preview folder with a visible mark before sending images to clients or collaborators.',
    scenario: 'A photographer, designer, or seller needs feedback on a large image set but does not want to distribute clean high-resolution masters before approval.',
    outcome: 'A clearly marked, review-sized sharing set while the clean masters remain untouched in a separate folder.',
    products: ['BWI'],
    inputs: ['Approved master image folder', 'Text or logo watermark', 'Sharing resolution and placement rules', 'A separate proof output folder'],
    steps: [
      { title: 'Keep masters separate', body: 'Treat the clean source folder as read-only. Create a dedicated proof output so there is no ambiguity about which files can be shared.' },
      { title: 'Choose a mark that matches the purpose', body: 'Use a clear “PROOF”, client name, logo, or review notice. A subtle brand mark and a strong proof overlay solve different problems.' },
      { title: 'Preview representative images', body: 'Test light, dark, portrait, landscape, and detail-heavy files. One corner position may disappear or cover important content across a mixed set.' },
      { title: 'Run the local batch', body: 'Use Batch Watermark Image to apply the approved text, logo, opacity, position, scale, or tiling across the folder.' },
      { title: 'Inspect before sending', body: 'Open several outputs at full size, verify the correct files were processed, and send only the proof folder.' }
    ],
    review: ['Are clean masters untouched?', 'Is the mark visible on both light and dark images?', 'Does it avoid covering essential detail?', 'Is only the proof folder being shared?'],
    limitation: 'A visible watermark can discourage casual reuse, but it cannot guarantee that an image will not be copied, cropped, edited, or recreated.',
    privacy: 'Watermarking is fully local. Source images and logo assets are not uploaded.',
    relatedUseCases: ['add-copyright-information-to-images', 'mass-create-social-media-content', 'create-posters-to-print-or-sell'],
    faq: [{ q: 'Should the watermark cover the centre?', a: 'For review proofs, a stronger central or tiled mark may be appropriate. For branded previews, a lighter edge placement may be less distracting. Test against the actual set.' }]
  }),
  useCase({
    id: 14,
    slug: 'add-copyright-information-to-images',
    title: 'Add Copyright Information to Images',
    shortTitle: 'Visible copyright batch',
    category: 'social',
    categoryLabel: 'Social & image production',
    summary: 'Apply a consistent visible creator, year, or rights notice across a published image collection.',
    scenario: 'A creator is preparing an online portfolio or campaign and wants every public copy to carry the same visible ownership line.',
    outcome: 'A separate publication folder with a legible, consistently placed visible copyright notice.',
    products: ['BWI'],
    inputs: ['Verified creator or rights-holder name', 'Correct year and notice wording', 'Placement and legibility rules', 'Clean master folder'],
    steps: [
      { title: 'Confirm the notice is accurate', body: 'Decide the exact visible line, such as a creator name and year. Do not imply ownership you do not hold, and remember that requirements differ by jurisdiction.' },
      { title: 'Design for readability', body: 'Choose a font size, colour, opacity, and position that remain legible without overwhelming the image. Test against the lightest and darkest examples.' },
      { title: 'Create publication copies', body: 'Use Batch Watermark Image to apply the verified text consistently to a separate folder. Preserve clean masters for print or later licensing.' },
      { title: 'Inspect the complete range', body: 'Check portrait, landscape, cropped, and differently coloured images. Adjust or split the batch if one setting does not work across the set.' },
      { title: 'Use other rights records too', body: 'Keep source files, creation records, contracts, and publication dates. A visible line is useful communication, not a complete rights-management system.' }
    ],
    review: ['Is the named rights holder correct?', 'Is the year deliberate?', 'Is the notice readable across the full set?', 'Are clean masters and provenance records preserved?'],
    limitation: 'This workflow adds visible text or a logo. It is not legal advice, copyright registration, invisible tracking, or a guarantee against unauthorised use.',
    privacy: 'The visible mark is added locally without uploading the image collection.',
    relatedUseCases: ['add-watermarks-before-sharing-images', 'batch-create-images-for-social-media', 'create-posters-to-print-or-sell'],
    faq: [{ q: 'Does adding © create or register copyright?', a: 'A visible notice communicates a claim; it is not a registration service and does not determine legal ownership. Consult reliable local guidance for your situation.' }]
  }),
  useCase({
    id: 15,
    slug: 'compress-images-to-save-storage-space',
    title: 'Compress Images to Save Storage Space',
    shortTitle: 'Compress an image archive',
    category: 'social',
    categoryLabel: 'Social & image production',
    summary: 'Create a lighter copy of an exported image collection for archiving, email, upload, or routine delivery.',
    scenario: 'A finished project folder contains hundreds of large exports. The files need to be emailed, backed up, or uploaded, but the current size makes that slow or expensive.',
    outcome: 'A separate compressed folder with a measured size reduction and a quality level that was visually approved.',
    products: ['BCI'],
    inputs: ['A clean source folder', 'The intended use: web, email, marketplace, or archive', 'A representative test group', 'A separate output location'],
    steps: [
      { title: 'Measure the source folder', body: 'Record total size, file count, formats, and the largest files. This gives the batch a measurable target rather than a vague “make it smaller” goal.' },
      { title: 'Protect the originals', body: 'Keep the original folder unchanged. Compression should create delivery or archive copies unless the loss is understood and accepted.' },
      { title: 'Test a representative subset', body: 'Use Batch Compress Image on detailed photos, flat graphics, gradients, and text-heavy images. One quality setting can affect these very differently.' },
      { title: 'Compare at real viewing size', body: 'Inspect edges, faces, text, gradients, and colour blocks. Choose the lightest acceptable setting for the intended destination, not the smallest file at any cost.' },
      { title: 'Run and measure the batch', body: 'Process the complete folder locally, then compare total size and spot-check outputs before uploading or archiving them.' }
    ],
    review: ['Was the original folder preserved?', 'Were different image types included in the test?', 'Is the quality acceptable at the real display size?', 'Is the size reduction recorded?'],
    limitation: 'Lossy compression removes information. Repeated compression can compound artifacts, and the best setting depends on image content and intended use.',
    privacy: 'Compression and comparison happen locally; the images do not need to leave the PC.',
    relatedUseCases: ['resize-images-for-different-social-platforms', 'organise-and-prepare-a-working-file-collection', 'create-posters-to-print-or-sell'],
    faq: [{ q: 'Should I compress before or after resizing?', a: 'Usually resize first, then compress the final delivery dimensions. That avoids carrying unnecessary pixels and lets you judge the actual published result.' }]
  }),
  useCase({
    id: 16,
    slug: 'enhance-images-for-printing',
    title: 'Enhance Images for Printing',
    shortTitle: 'Prepare images for print',
    category: 'social',
    categoryLabel: 'Social & image production',
    summary: 'Upscale a selected image set against real print dimensions and inspect the result before ordering.',
    scenario: 'A strong image looks good on screen but its pixel dimensions are too small for a photobook page, poster, or product print.',
    outcome: 'A locally processed print folder at the required dimensions, plus a proof decision for each selected image.',
    products: ['BEI'],
    inputs: ['Final physical size', 'Printer’s pixel, bleed, colour, and file requirements', 'Selected source images', 'A plan for test prints'],
    steps: [
      { title: 'Calculate the target', body: 'Start from the printer’s current specification and physical dimensions. DPI metadata alone does not create detail; pixel dimensions are what determine available image data.' },
      { title: 'Select before enhancing', body: 'Do not upscale an entire generation folder. Remove weak, duplicate, and defective images first so time is spent only on genuine candidates.' },
      { title: 'Choose a controlled scale', body: 'Use Batch Enhance Image with the smallest scale that reaches the target. Stronger enlargement can make existing defects more obvious.' },
      { title: 'Inspect at full resolution', body: 'Check faces, hands, lettering, fine edges, textures, and smooth gradients. Compare the output to the source and reject files that become artificial or over-sharpened.' },
      { title: 'Order a representative proof', body: 'Print one or more difficult images at the actual size. Check crop, sharpness, colour, and viewing distance before committing to a complete run.' }
    ],
    review: ['Are target pixel dimensions based on the printer specification?', 'Were only selected images processed?', 'Were artifacts checked at full resolution?', 'Was at least one physical proof reviewed?'],
    limitation: 'Enhancement can enlarge and improve presentation, but it cannot recover detail that was never present or fix bad anatomy, composition, or heavy compression.',
    privacy: 'The enhancement workflow is fully local.',
    relatedUseCases: ['create-a-photobook-with-ai-for-gifting', 'create-posters-to-print-or-sell', 'create-a-colouring-book-for-children'],
    faq: [{ q: 'Is setting 300 DPI enough?', a: 'No. The image also needs enough pixels for the physical dimensions. DPI metadata without sufficient pixel dimensions does not add real detail.' }]
  }),
  useCase({
    id: 17,
    slug: 'resize-images-for-different-social-platforms',
    title: 'Resize Images for Different Social Platforms',
    shortTitle: 'Platform-specific image sizes',
    category: 'social',
    categoryLabel: 'Social & image production',
    summary: 'Turn one approved master set into channel-specific dimensions without manually resizing every image.',
    scenario: 'A campaign is visually approved, but Instagram, X, LinkedIn, and other channels need different aspect ratios and crops.',
    outcome: 'Clearly separated platform folders created from one protected master set, with important crops reviewed by a person.',
    products: ['BRI'],
    inputs: ['Approved master images', 'Current platform dimension requirements', 'Crop priorities for faces, products, and text', 'Destination folder naming'],
    steps: [
      { title: 'Verify current channel requirements', body: 'Platform specifications change. Confirm the formats and placements you are actually publishing before creating presets or output folders.' },
      { title: 'Protect the master set', body: 'Keep one approved source folder. Every platform version should be reproducible from those masters rather than resized from an already resized copy.' },
      { title: 'Create one channel batch at a time', body: 'Use Batch Resize Image with the target dimensions and crop behavior. Write each result to a clearly named platform folder.' },
      { title: 'Inspect sensitive crops', body: 'Review images containing faces, products, logos, and on-image text. Automatic crop rules cannot know what is semantically important.' },
      { title: 'Test in the publishing interface', body: 'Upload a small sample or preview it in the platform’s composer. Feed corrections back into the resize setup before processing future campaigns.' }
    ],
    review: ['Were current platform requirements verified?', 'Did every output come from the master set?', 'Are important subjects preserved in the crop?', 'Are platform folders unambiguous?'],
    limitation: 'One composition cannot always be adapted cleanly to every aspect ratio. Some images need manual crops or a separately composed version.',
    privacy: 'Resizing happens locally. Platform upload occurs only when you choose to publish.',
    relatedUseCases: ['mass-create-social-media-content', 'batch-create-images-for-social-media', 'compress-images-to-save-storage-space'],
    faq: [{ q: 'Can I use one preset forever?', a: 'No. Platform recommendations and placements change, so verify current requirements when a campaign matters.' }]
  }),
  useCase({
    id: 18,
    slug: 'merge-pdfs-without-using-the-internet',
    title: 'Merge PDFs Without Using the Internet',
    shortTitle: 'Merge PDFs locally',
    category: 'files',
    categoryLabel: 'PDF & file workflows',
    summary: 'Combine chapters, scans, reports, or exported sections into one predictable PDF while the documents stay on the PC.',
    scenario: 'A folder contains several PDFs that belong in one delivery packet, but the documents are private or too large for an online merge service.',
    outcome: 'One locally produced PDF in a filename-controlled order, with optional continuous page numbers.',
    products: ['BMP'],
    inputs: ['A folder containing only the PDFs to merge', 'Numbered filenames that express the order', 'An output location', 'A decision about new page numbers'],
    steps: [
      { title: 'Prepare a clean merge folder', body: 'Copy the intended PDFs into one working folder. Remove unrelated documents and keep the source originals elsewhere.' },
      { title: 'Make the order explicit', body: 'Rename the files with zero-padded prefixes such as 01-cover, 02-summary, and 03-report. Batch Merge PDFs uses alphabetical filename order.' },
      { title: 'Decide how page numbers should work', body: 'Add fresh continuous page numbers only if the final packet needs them. Do not add a second set when the source documents already contain required numbering.' },
      { title: 'Run the local merge', body: 'Choose the source folder and output location in Batch Merge PDFs, review the PDF count, and start the merge.' },
      { title: 'Inspect the final document', body: 'Open the result and check first page, last page, section transitions, orientation, order, and page numbering before delivery.' }
    ],
    review: ['Does the folder contain only intended PDFs?', 'Do filenames sort into the exact required order?', 'Are page numbers necessary and correct?', 'Were the first, last, and transition pages checked?'],
    limitation: 'The app combines PDFs; it does not repair corrupted documents or decide the semantic order for you. Filename preparation is part of the workflow.',
    privacy: 'Merging runs locally and does not upload the PDFs.',
    relatedUseCases: ['batch-create-pdfs-from-text', 'translate-a-book-for-new-markets', 'create-a-poetry-book'],
    faq: [{ q: 'Why did my files merge in the wrong order?', a: 'The merge follows alphabetical filenames. Use consistent zero-padded numeric prefixes to make the intended order explicit.' }]
  }),
  useCase({
    id: 20,
    slug: 'batch-create-pdfs-from-text',
    title: 'Batch-Create PDFs From Text',
    shortTitle: 'Batch text-to-PDF',
    category: 'files',
    categoryLabel: 'PDF & file workflows',
    summary: 'Convert a folder of Markdown, text, DOCX, or images into separate PDFs or one ordered document.',
    scenario: 'A writer, teacher, or small team has chapters, worksheets, guides, notes, and illustrations in a folder and needs consistent PDFs without converting each file manually.',
    outcome: 'One PDF per supported source or one combined, page-numbered document created locally with a repeatable page setup.',
    products: ['BTP'],
    inputs: ['Supported source files in one folder', 'Filename order for combined mode', 'Page size, margins, and numbering choice', 'Optional same-named text and image pairs'],
    steps: [
      { title: 'Prepare the source folder', body: 'Place supported Markdown, TXT, DOCX, and image files directly inside one working folder. Use numbered filenames when combined output must follow a specific order.' },
      { title: 'Choose separate or combined output', body: 'Use per-file mode for individual handouts, notes, or client documents. Use combined mode for chapters, story pages, or one ordered report.' },
      { title: 'Set the page system', body: 'Choose a built-in document or book preset, or enter exact custom dimensions and margins. Decide whether page numbers belong in the output.' },
      { title: 'Pair text and illustrations when useful', body: 'Give a text file and image the same base filename, then choose whether the image appears before or after the text and inline or on its own page.' },
      { title: 'Run and inspect the conversion log', body: 'Review converted, skipped, renamed, and failed counts. Open the output folder and inspect multilingual text, emoji, image placement, and page breaks.' },
      { title: 'Correct the source, then rerun', body: 'Fix Markdown, filenames, page settings, or source text rather than patching every final PDF manually. Skip-existing support helps preserve approved outputs during a rerun.' }
    ],
    review: ['Are filenames correct for combined order?', 'Do page size and margins match the use?', 'Are paired images attached to the right text?', 'Were skipped and renamed files reviewed?'],
    limitation: 'DOCX conversion extracts paragraph text but does not reproduce Word styling, page layout, or embedded images. Animated GIFs become static image pages, and existing PDFs are skipped.',
    privacy: 'Core conversion is local and requires no AI service, upload, account, analytics, or telemetry.',
    relatedUseCases: ['merge-pdfs-without-using-the-internet', 'create-short-stories-for-teaching', 'create-a-poetry-book'],
    faq: [
      { q: 'Can it preserve Markdown formatting?', a: 'Yes. It renders supported Markdown formatting and relative local images.' },
      { q: 'Can it combine the whole folder?', a: 'Yes. Combined mode processes supported source files in filename order.' }
    ]
  }),
  useCase({
    id: 21,
    slug: 'organise-and-prepare-a-working-file-collection',
    title: 'Organise and Prepare a Working File Collection',
    shortTitle: 'Clean a project folder',
    category: 'files',
    categoryLabel: 'PDF & file workflows',
    summary: 'Clean a Downloads, publishing, or image-output folder before archiving, sharing, or starting the next workflow.',
    scenario: 'A project folder contains source files, duplicates, drafts, generated outputs, and delivery copies. Nobody can confidently tell what should be kept or reused.',
    outcome: 'A reviewed local folder structure with exact duplicates identified, intended files organised, and the last operation still reversible.',
    products: ['BFO', 'BCI', 'BEI'],
    inputs: ['A copied working folder rather than the only archive', 'A desired type- or date-based structure', 'Rules for exact duplicates', 'A plan for source, working, and delivery files'],
    steps: [
      { title: 'Create a safe working copy', body: 'Do not begin a large cleanup on the only copy of important work. Make or verify a backup and identify which folder is in scope.' },
      { title: 'Scan before moving anything', body: 'Use Batch File Organiser to inspect file types and exact duplicate results. Hash matches can reveal identical files even when names differ.' },
      { title: 'Preview the proposed structure', body: 'Choose type or date organisation and examine the complete plan. Look for project conventions that automated grouping should not override.' },
      { title: 'Apply one understandable operation', body: 'Run the approved organisation step locally. Verify representative folders immediately while the undo context is still clear.' },
      { title: 'Separate masters from delivery copies', body: 'Keep high-quality sources distinct from resized, compressed, watermarked, or enhanced outputs. This prevents accidental quality loss in later work.' },
      { title: 'Prepare only the files that need it', body: 'Use Batch Compress Image for lighter delivery or archive copies and Batch Enhance Image for selected print files. Neither action is a substitute for folder organisation.' }
    ],
    review: ['Is there a backup or safe working copy?', 'Were duplicate matches inspected before removal decisions?', 'Does the preview respect project-specific folders?', 'Are masters separated from derived outputs?'],
    limitation: 'Hash matching identifies exact duplicates, not the “best” edit. Organisation rules cannot infer every project convention, so preview and backup remain important.',
    privacy: 'Scanning, hashing, moving, compression, and enhancement run locally.',
    relatedUseCases: ['compress-images-to-save-storage-space', 'enhance-images-for-printing', 'merge-pdfs-without-using-the-internet'],
    faq: [{ q: 'Does duplicate detection decide which copy to delete?', a: 'It identifies exact matches. You still decide which path or copy belongs in the final structure.' }]
  })
];
